### ISSUE TITLE
Remove path on parameter annotation

### ISSUE THREAD

**Issue by rossmechanic** [mkdocstrings/mkdocstrings#115]
Hi @pawamoy, sorry to keep bothering you! Our annotations can sometimes be quite long, and I'd love to remove the path prepending the annotation. Any thoughts on best way to do this?

**Comment by rossmechanic** [comment]
Any chance we could add a `replace_regex` filter to the jinja environment to let developers handle this on our own?

**Comment by pawamoy** [comment]
Hey @rossmechanic, you are not bothering me, please do continue helping to improve mkdocstrings :wink:!

Yup, I saw that too in some of my own projects, sometimes the annotations are "full paths" and sometimes just the "base path". Not sure why.

> Any chance we could add a replace_regex filter to the jinja environment to let developers handle this on our own?

I like the idea. Though I'd go with a more generic approach, and let the user "load" their own filters.

Ideally, we would implement https://github.com/pawamoy/pytkdocs/issues/12 and https://github.com/pawamoy/pytkdocs/issues/13, which would allow mkdocstrings to easily display just the base name, with a link to object in the docs!

I'm actually progressing in that direction with the current refactoring of the attributes parser of pytkdocs: https://github.com/pawamoy/pytkdocs/issues/30 (spec in https://github.com/pawamoy/pytkdocs/issues/33).

**Comment by rossmechanic** [comment]
Letting the user "load" their own filters would be great! @pawamoy . Happy to help contribute where you need support

**Comment by pawamoy** [comment]
Well if you have suggestions on how we could allow users to load their own filters in the Jinja env, I'm all ears! Obviously we would need to add a new option to mkdocstrings. It could accept a filepath or a python dotted-path. The python code is the specified module would use `register` functions maybe, that would store the filters somewhere so they can be injected into the Jinja env. What do you think?

**Comment by pawamoy** [comment]
Additionally, what builtin filters do you think mkdocstrings could provide? What are the most common things users would want to use in custom templates?

**Comment by rossmechanic** [comment]
I think a path directly to a filter or a module with filters would make a lot of sense. I honestly care a lot less about the built-in filters (it doesn't feel like that's this library's responsibility) than I do about the ability to provide my own filters. 

Basically I think the project would benefit from a having a few more hook for custom features. I.e. we could add more blocks within the templates so that developers can replace smaller pieces without having to replace entire templates. I think custom filters falls along those same lines. I don't think it's on you to build out any builtin filters beyond what you currently use

**Comment by pawamoy** [comment]
The new Python handler now has a `annotations_path` option to render annotations as written in the source, or a brief version (only the last components). See https://mkdocstrings.github.io/python/usage/#globallocal-options
