### ISSUE TITLE
Formatting objects differently depending on their inheritance 

### ISSUE THREAD

**Issue by stufisher** [mkdocstrings/mkdocstrings#130]
**Is your feature request related to a problem? Please describe.**
For models and schemas it would be nice to display these in table format, rather than the current list of headers. I realise this makes sense for normal classes, but it is very verbose for a model class like pydantic, dataclasses, and marshmallow. I would like to show these in a more compact format.

**Describe the solution you'd like**
Markdown table would be good

**Additional context**
If you point me in the right direction i could look at adding a per class type jinja template or something?
Related to https://github.com/pawamoy/pytkdocs/pull/51

**Comment by pawamoy** [comment]
Already possible! Instead of using individual docstrings, use an `Attributes` section in the class docstring:

```python
class MyModel(BaseModel):
    """
    My model.

    Attributes:
        v1: Hello.
    """
    
    v1: str
```

**Comment by pawamoy** [comment]
Please reopen if it doesn't work as you would like.

**Comment by stufisher** [comment]
With marshmallow i dont use docstrings at all, and i really dont want to add them as they add significant duplication. It seems to be fairly common place to describe the field as so:

```
class MySchema(Schema):
    v1 = fields.Str(description="Hello")
```

This keeps the code pretty succinct, and these are easily transformed into jsonschema where description can be reused on the front end. For the marshmallow implementation i added i take `description` from the field metadata and pass that as the docstring.

Therefore i think for these specific types of classes i would like to override the renderer template. I could do something as simple as allowing (and maybe autodetecting model class types?)
```
renderer:
    template: table
```

**Comment by pawamoy** [comment]
I see, you make valid points :slightly_smiling_face: 

Then yes, you can use [custom templates](https://pawamoy.github.io/mkdocstrings/usage/#templates)
to achieve what you want.

You could override the [`class.html` template](https://github.com/pawamoy/mkdocstrings/blob/master/src/mkdocstrings/templates/python/material/class.html) to check if the class has a `marshmallow-model` property and render its attributes in a table before the other children. To render the attributes, you would define a new template, something like `marshmallow_attributes.html`, that would look like the [`attributes.html` one](https://github.com/pawamoy/mkdocstrings/blob/master/src/mkdocstrings/templates/python/material/attributes.html).

Something like this:

```
     ... previous contents

      {% if "marshmallow-model' in class.properties %}
        {% with attributes = class.attributes %}
          {% include "marshmallow_attributes.html" with context %}
        {% endwith %}
      {% endif %}

      {% with obj = class %}
        {% set root = False %}
        {% set heading_level = heading_level + 1 %}
        {% include "children.html" with context %}
      {% endwith %}

    ... next contents
```

**Comment by pawamoy** [comment]
Also I like the

```
rendering:
  template:
```

This is tracked in https://github.com/pawamoy/mkdocstrings/issues/105

**Comment by pawamoy** [comment]
I opened this feature request to support Marshmallow: https://github.com/mkdocstrings/griffe/issues/339. Closing this issue since there's nothing actionable here I believe.
