### ISSUE TITLE
Examples section does not understand numbered code examples well

### ISSUE THREAD

**Issue by chbndrhnns** [mkdocstrings/mkdocstrings#138]
**Describe the bug**
Putting code snippets under numbered lines in the Examples section does not render them as code examples (or fails at all with smartypants enabled due to https://github.com/pawamoy/mkdocstrings/issues/129).

**To Reproduce**
Try this example:

```python
def method():
    """
    Bla

Examples:
        1. Do this

            >>> print('this')

        2. Do that

            >>> print('that')

        3. Third step

        4. Fourth step    
"""

```

**Expected behavior**

**Screenshots**
![Screenshot 2020-07-23 11 05 09](https://user-images.githubusercontent.com/7534547/88269506-6f42c000-ccd4-11ea-824b-89cac8e6e476.png)

**Information (please complete the following information):**
- OS: macOS
- Browser: Chrome
- `mkdocstrings` version: 0.12.1

**Additional context**

**Comment by xgui3783** [comment]
IIRC, `>` is interpreted as block quotes. 

If you want to pretty print codes, you might want to

```
def method():
    """
    Bla

Examples:
        1. Do this
            ```
            >>> print('this')
            ```
        2. Do that
            ```
            >>> print('that')
            ```
        3. Third step

        4. Fourth step    
"""
```

**Comment by chbndrhnns** [comment]
Oh yes, of course, that's the explanation. However, by putting it in quotes, python will not run it as doctests and I really would like to see that my examples are up-to-date.

**Comment by jaredkhan** [comment]
You can have it rendered as code without the triple backticks by adding yet another level of indentation to mark it as a code block:

```

def method():
    """
    Bla

        >>> code here

    Examples:
        1. Do this (note the number of spaces!)

                >>> print('this')

        2. Do that

                >>> print('this')

        3. Third step

        More words here

        4. Fourth step
    """
    pass

```

**Comment by chbndrhnns** [comment]
@jaredkhan So I misunderstood your comment on my other issue, it seems. Now that I have tried with two levels of indentation, I see this result which is better but the syntax highlighting is missing for the numbered code parts:

![Screenshot 2020-07-23 11 30 19](https://user-images.githubusercontent.com/7534547/88271732-e4fc5b00-ccd7-11ea-8813-24548185b78e.png)

**Comment by pawamoy** [comment]
Hi again :)

So this is a bit tricky: you have doctests in a ordered list. To keep the numbering, you need indentation on the doctests. But to keep the Python syntax highlight, you must not use indentation!

Could you try to somehow *escape* your numbered items, and write everything at the same level of indentation?

```
\1. Item 1

>>> doctest1

\2. Item 2

...
```

**Comment by pawamoy** [comment]
Another solution would be to specify a better way to parse indented doctests, and send a PR to pytkdocs :slightly_smiling_face:

**Comment by chbndrhnns** [comment]
> Could you try to somehow _escape_ your numbered items, and write everything at the same level of indentation?

Escaping the numbers would remove them from the rendered docs here and just leave the dots.

**Comment by pawamoy** [comment]
This is now possible thanks to the [Markdown PyCon extension](https://pawamoy.github.io/markdown-pycon/), which is immediately available to my sponsors, and has been added to the [GraviFridge goal](https://pawamoy.github.io/insiders/#1000-gravifridge-user-manual) :slightly_smiling_face:
