### ISSUE TITLE
Is there a way to add custom default value for a parameter in class documentation?

### ISSUE THREAD

**Issue by kennychowdhary** [mkdocstrings/mkdocstrings#145]
**Is your feature request related to a problem? Please describe.**
I want to be able to define a custom default for a parameter within the main class documentation. I know how to manually add a type, but not a default value. I can add it to the constructor __init__ method and it works fine, but wondering if it can be done outside the __init__.  

```
class Test():
       """
	Parameters:
		X (float):	Data matrix
       """
```

**Describe the solution you'd like**
Something like this or just as simple?
```
class Test():
       """
	Parameters:
		X (float):	Data matrix, default=1
       """
```

**Comment by pawamoy** [comment]
Hey @kennychowdhary, I'm very sorry to answer so late :bowing_man: 
There's no current way to do that.
I'm not sure what you are doing in your code, to provide a default but not in the `__init__` method.
The best thing to do anyway is to document it in a docstring.

My understanding is the following:

```python
class A:
    def __init__(self, value=None):
        value = value or [0]  # you probably want to document that default value
        # then you should document it in in the class docstring or the constructor docstring
        # something like: when value is `None`, it will be set to `[0]`.
```

I'll say that it's not in the scope of pytkdocs or the new tool I'm working on that will replace pytkdocs. If you can present more use-cases, I will consider them and maybe reopen :slightly_smiling_face:
