### ISSUE TITLE
Include only specific inherited members

### ISSUE THREAD

**Issue by chrieke** [mkdocstrings/mkdocstrings#157]
**Is your feature request related to a problem? Please describe.**
My class `A` that I want to document is inheriting functions from a base class `Base`. However, for class `A` I only want to add a subset of the functions of `Base` to the docs. I can use `inherited_members: true` and then filter out the functions I don't want to use. But when doing this for multiple modules it becomes a bit messy and means I always have to check when adding new functionality in the code.

**Describe the solution you'd like**
I'd like `inherited_members` to work exactly like `members`. Instead of just `bool`, it can be `bool, or list of str`. This way I could define the specific inherited functions I want to include. The default could still be `False`.

```
::: classA
    selection:
      inherited_members:
        - inherited_method_a
        - inherited_method_b
```

**Comment by pawamoy** [comment]
What would be the behavior if `inherited_members` is `True` and `members` is a list of names? Should *all* the inherited_members be selected, regardless of the filters in `members`?

**Comment by chrieke** [comment]
::: classA
    selection:
      members:
        - method_a
        - method_b
      inherited_members: True

Would `inherited_method_a` be included or not?

Good question, yes, intuitively I would say that this would mean that all inherited members are selected. `members` and `inherited_members` would be two independent selections. Only downside I see right now is that after the update it could be missonfigured a bit for people who currently filter inherited functions via `members`.

**Comment by pawamoy** [comment]
Sorry, it seems I referenced the wrong issue in the linked PR :confused:

**Comment by pawamoy** [comment]
Okay this is really implemented now :slightly_smiling_face:
