### ISSUE TITLE
Allow using "import" path of an object rather than the "real path" (where it was defined)

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#178]
**Is your feature request related to a problem? Please describe.**
Use-cases:
- defining objects in private submodules, importing them in another public facing module.
- importing objects in `__init__.py` modules

Witnessed in #168 and other issues on GitHub.

Since pytkdocs resolves to the real path, these use case are not possible.

**Describe the solution you'd like**
Allow documenting objects from any path.

**Additional context**
pytkdocs will still need to resolve the real path for attributes because it needs to parse their code to find docstrings and type annotations. The real path could be kept in an additional data field for these cases.

**Comment by pawamoy** [comment]
Feature request on pytkdocs: https://github.com/pawamoy/pytkdocs/issues/74

**Comment by oprypin** [comment]
Somewhat related thing that I first brought up in chat. For Python, as you're describing here, an item could be available under multiple import paths, whereas in Crystal there is no namespacing per-file, but there's a feature to explicitly add an alias of a type under another name.

> I'm currently running into an issue where an object can be resolved under more than one name (has an alias), however, the cross-reference-fixer cannot pick up on that, it only knows about the final HTML id.
>
> I understand why that happens, but my wish is that the xref fixer would also ask the collector whether it has a canonical id for this item and look for that id.
>
> Seems like it would have to be a hack like... after trying `url_map` it would also do `for handler in handlers_cache.items(): url_map[handler.canonical_url(identifier)]`

**Comment by pawamoy** [comment]
Well, I'm always in favor of something that makes the code less Python-specific and more language-agnostic, so why not having this canonical ID thing :slightly_smiling_face:

**Comment by corykinney** [comment]
I've been trying to figure out how to have code organized in private submodules with a public interface documented and finally found this issue. Is this still something that might get implemented?

**Comment by pawamoy** [comment]
It is, yes, and it requires some changes on pytkdocs side (for which I couldn't dedicate time yet).

**Comment by wxdrizzle** [comment]
Hi, I noticed that this issue was mentioned as a [pytkdocs issue](https://github.com/mkdocstrings/pytkdocs/issues/74) which is still open, while it was "added to 0.11 in Roadmap" of pytkdocs and seems that the newest version is already 0.12. Then, has this issue been solved? Thank you!

**Comment by pawamoy** [comment]
Hello :slightly_smiling_face: 
I just removed the pytkdocs Roadmap project. I never had the resources to properly follow that roadmap, it was only misleading. So, no, this issue has not been solved *in pytkdocs*. But there's a new Python handler coming (I'm slowly advertising it) which supports this :slightly_smiling_face: It will be based on [griffe](https://github.com/pawamoy/griffe) instead of pytkdocs. There's still work to do, but it's going well.

**Comment by pawamoy** [comment]
Oh, and latest pytkdocs is 0.15.0, you might want to update mkdocstrings to 0.17.0 so it accepts it.

**Comment by wxdrizzle** [comment]
That's great! Thank you for all the work!

**Comment by pawamoy** [comment]
.........and the new handler is available! See details here: https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers.

With the new handler users are able to document objects using their public path rather than their canonical path.
Such public imports should be added to the `__all__` variable of the given module to make sure they are correctly resolved and rendered.

I believe we can close this issue, feel free to further comment on this.

**Comment by posita** [comment]
> With the new handler users are able to document objects using their public path rather than their canonical path. Such public imports should be added to the `__all__` variable of the given module to make sure they are correctly resolved and rendered.

To be clear, this still won't work if I have something like the following, though, correct?

``` python
# mylib/__init__.py
from .mymod import *
```

``` python
# mylib/mymod.py
__all__ = ("THING",)
THING = "THING"
```

In the above, mkdocstring won't be able to see `mylib.THING` until I _also_ add it to `__all__` inside `mylib/__init__.py`, correct?

**Comment by WillDaSilva** [comment]
One option is to update `__all__` in `mylib/__init__.py` using `mylib.mymod.__all__`:

```python
from . import mymod
from .mymod import *


__all__ = sorted([
    'something',
    'another',
    'mymod',
    *mymod.__all__,
])
```

**Comment by pawamoy** [comment]
No no, your example should totally work. `mylib.mymod.__all__` is exactly used to expand the wildcard import in `mylib` :slightly_smiling_face: 

So everything that `mylib.mymod` "exports" using its `__all__` variable will be part of `mylib`.
