### ISSUE TITLE
Wrap functions, variables, etc in docstrings with backticks?

### ISSUE THREAD

**Issue by TensorTom** [mkdocstrings/mkdocstrings#181]
Possible to wrap objects such as `functions()`, known `variables`, etc. that are referenced in docstrings with `backticks`?

**Comment by pawamoy** [comment]
Do you mean you want to be able to cross-reference objects by wrapping them in backticks?

**Comment by oprypin** [comment]
Could also mean rendering "[Foo][]" as <code><a href="#Foo">Foo</a></code> rather than <a href="#Foo">Foo</a>. Currently I think the latter is possible only as "[\`Foo\`][Foo]"

**Comment by pawamoy** [comment]
Yes, ``[`Foo`][Foo]`` is the only way to do this yet. Maybe we could consider adding an option to always wrap cross-references in `<code>` tags.

**Comment by oprypin** [comment]
Hmm how about supporting ``[`Foo`][]`` as being ``[`Foo`][Foo]``? It'd be backwards compatible and I found myself wishing for it.

**Comment by pawamoy** [comment]
Could be nice, yes! Are there languages with backticks in objects identifiers :stuck_out_tongue:?

**Comment by pawamoy** [comment]
I believe this was implemented in one of your latest PR @oprypin? It will be released in 0.16.
