### ISSUE TITLE
Support for documentation of **kwargs

### ISSUE THREAD

**Issue by sansbacon** [mkdocstrings/mkdocstrings#205]
I'm using Google-style docstrings and providing documentation on **kwargs
```
       Crossover operation to generate new population

        Args:
            None
            
        Keyword Args:
            agg (bool): if True, then aggregate multiple crossovers, otherwise is sequential.
            population (np.ndarray): the population to cross over, is 2D array
            population_fitness (np.ndarray): the fitness of the population to crossover, is 1D array
            pctl (int): the percentile fitness (1-99) to use in crossover, default 50 

        Returns:
            np.ndarray

```

However, the docstring ends up looking like this when processed by mkdocstrings

```
crossover(self, **kwargs)
Crossover operation to generate new population

Keyword Args: agg (bool): if True, then aggregate multiple crossovers, otherwise is sequential. population (np.ndarray): the population to cross over, is 2D array population_fitness (np.ndarray): the fitness of the population to crossover, is 1D array pctl (int): the percentile fitness (1-99) to use in crossover, default 50

!!! returns np.ndarray
```

Is there a workaround or is it possible to support the Keyword Arguments section?

Best regards,
Eric

**Comment by pawamoy** [comment]
I don't see any reference to a possible "Keyword Args" section in the [Google style guide](https://google.github.io/styleguide/pyguide.html) for Python. If you do, could you share a link?

In any case, you can document your `**kwargs` in the "Args" section, like any other argument:

```
       Crossover operation to generate new population

        Args:
            **kwargs:
                - agg (bool): if True, then aggregate multiple crossovers, otherwise is sequential.
                - population (np.ndarray): the population to cross over, is 2D array
                - population_fitness (np.ndarray): the fitness of the population to crossover, is 1D array
                - pctl (int): the percentile fitness (1-99) to use in crossover, default 50 

        Returns:
            np.ndarray
```

Note however that this is written in Markdown, and won't appear as *a table in a table* (unless you use the markup for a table).

**Comment by gegnew** [comment]
It's supported by [napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html#docstring-sections), and I'd definitely second the option to specify a Keyword Args section.

As it is, if you have a lot of kwargs that you don't want in your function definition, but you do want in the docstring...

```
def my_function(arg1, arg2, **kwargs):
    """
    Args:
        arg1: foo
        arg2: bar
        kwarg1 (str) = 'one'
        kwarg2 (int) = 2
    """
    pass
```

Then the table is rendered with the "Default" column as "_required_" for those kwargs

**Comment by pawamoy** [comment]
Ah, thank you for the Napoleon page, it's helpful :slightly_smiling_face: Then we can indeed consider adding support for "Keyword Arguments" sections :slightly_smiling_face:

**Comment by pawamoy** [comment]
Implemented in https://github.com/mkdocstrings/pytkdocs/pull/105, will be available in the next releases of mkdocstrings/pytkdocs.

**Comment by fowlball1010** [comment]
Hi, I was wondering if this feature should be in the latest mkdocstrings (v0.16.2). I've downloaded the latest from pip and attempted to use the `Keyword Args` capability, but to no avail. I've included a screenshot of the rendering of my page. Also, the python code with the documentation is outlined below:

```
class TestClass():
    def __init__(self, test="blah", **kwargs):
        """Summary line.
        
        Extended description of function.
        
        Args:
            test (str): Test argument
            
        Keyword Arguments:
            kwarg_one (str): Test kwarg argument
            
        Returns:
            None
            
        """
```

![Test Module](https://user-images.githubusercontent.com/2672811/135877025-754db688-13c1-4e79-aa17-ebb0148d20f7.png)

**Comment by pawamoy** [comment]
Arf, indeed! Then I'll finish adding support for Yields in pytkdocs and then update mkdocstrings to support both yields and keyword args section! Sorry and thank you for the reminder :sweat_smile:

**Comment by fowlball1010** [comment]
Hi, I just wanted to follow up from my original comment. Should this feature be fully integrated into the baseline now? It looked like perhaps a pipeline failure was preventing the fix from being integrated?

**Comment by pawamoy** [comment]
Not sure what pipeline you are talking about, but yes, this should be fully supported now :slightly_smiling_face:
