### ISSUE TITLE
CSS classes for just attribute/class/method/function name part of signature

### ISSUE THREAD

**Issue by jayqi** [mkdocstrings/mkdocstrings#240]
**Is your feature request related to a problem? Please describe.**

There is currently not a straightforward way to specify CSS selectors to just grab attribute/class/method/function names for styling. For example, I decided to style my docs' headers such that the names are bolded but not the rest of the signature like the type hints and arguments.

<img src="https://user-images.githubusercontent.com/2721979/108804421-18df7d80-7552-11eb-86ac-ed062c1498d3.png" width="480px" />

**Describe the solution you'd like**

CSS classes for the names of attribute/class/method/function signatures

**Describe alternatives you've considered**

Currently, I'm using a work around by first selecting all span elements inside `doc-heading` and styling them and then selecting all spans except the first and **un**styling them. This is approach is obtuse and feels fragile—I'd much rather achieve this declaratively. 

Example: 
- CSS: [link](https://github.com/jayqi/reprexlite/blob/38d5951aa4c06733f05eef3db81018afd6cae8c6/docs/docs/stylesheets/custom_mkdocstrings.css#L22-L29)
- Rendered: https://jayqi.github.io/reprexlite/api-reference/formatting/

**Comment by pawamoy** [comment]
Maybe we could use spans. Note that you can also override the `signature.html` template to add these spans yourself, while waiting for something that better suits your needs :smile:

**Comment by pawamoy** [comment]
> Currently, I'm using a work around by first selecting all span elements inside doc-heading and styling them and then selecting all spans except the first and unstyling them. 

Couldn't you simply select the first span then?
https://www.w3schools.com/cssref/sel_firstchild.asp
Something like 

```css
.doc.doc-heading span:first-child {
    font-weight: bold;
}
```

**Comment by jayqi** [comment]
It's been a while and I don't recall the details exactly, but I remember reading this StackOverflow answer about how `first-child` worked and that it may not have done what I wanted. https://stackoverflow.com/a/8539107

**Comment by pawamoy** [comment]
The new Python handler now add these CSS classes to spans containing objects names in headings:

- doc
- doc-object-name
- doc-KIND-name

...KIND being attribute, function, class or module.

Closing, feel free to reopen :slightly_smiling_face:
