### ISSUE TITLE
Inventory Object (like in sphinx)

### ISSUE THREAD

**Issue by FalseDev** [mkdocstrings/mkdocstrings#251]
**Is your feature request related to a problem? Please describe.**

**Background:** I'm making [a discord bot for developers](https://github.com/FalseDev/Tech-Struck) that has an RTFM command (searches through docs).

**How it works:** [Sphinx](https://www.sphinx-doc.org/) generates an `objects.inv` file which can be fetched and used like an index, I use this to build an index of all documentation  under a module and search through it

**My Problem:** Currently mkdocstring doesn't (as far as I know) produce any similar *index/inventory* object

 **Describe the solution you'd like**

The ideal solution would be making mkdocstrings create an inventory (`objects.inv`) object fully compatible with sphinx

**Describe alternatives you've considered**
I could use web scraping, but it's much more resource intensive and takes longer, so I couldn't use it here

**Comment by pawamoy** [comment]
Hi @FalseDev, thanks for opening this :slightly_smiling_face: We have plans for this, yes! I think it would even make sense to implement it in mkdocstrings first, and then use it in pytkdocs/mkdocstrings for automatic cross-documentation links :slightly_smiling_face:

**Comment by pawamoy** [comment]
Implemented in #253 :slightly_smiling_face:
