### ISSUE TITLE
templates/python/material/attributes.html not working

### ISSUE THREAD

**Issue by JesseWebDotCom** [mkdocstrings/mkdocstrings#256]
I don't think the attributes template file is working:
https://github.com/mkdocstrings/mkdocstrings/blob/master/src/mkdocstrings/templates/python/material/attributes.html

I currently have custom_templates enabled with the material theme for a python project - other template files work fine.  With the attributes.html, changes in the file never get rendered in the final documentation.

Steps:

1. Enable templates:
```
plugins:
  - mkdocstrings:
      custom_templates: templates
```
2. Copy https://github.com/mkdocstrings/mkdocstrings/tree/master/src/mkdocstrings/templates to your projects templates directory
3. Modify templates/python/material/attributes.html - Change "Attributes:" to "Attributes CHANGED "
4. Modify templates/python/material/attribute.html - Change "{% if attribute.type %}: {{ attribute.type }}{% endif %}" to "{% if attribute.type %} CHANGED {{ attribute.type }}{% endif %}"
5. Run 'MkDocs serve', open the dev docs web server url, and browse to a page with attributes

You should see the changes are working in the attribute.html but are not working in the attributes.html

**Comment by pawamoy** [comment]
Hello @JesseWebDotCom!

Unfortunately I can't reproduce, it's working on my end:

```python
class Collection:
    """
    A collection of duties.

    Attributes:
        path: The path to the duties file.
        duties: The list of duties.
        aliases: A dictionary of aliases pointing to their respective duties.
    """
```

![Screenshot_2021-03-17_20-15-58](https://user-images.githubusercontent.com/3999221/111525352-cf9fd980-875d-11eb-88d0-5426f48bd2df.png)

**Comment by JesseWebDotCom** [comment]
Sorry, the issue was the attributes area I needed to modify was children.html file.  Once I discovered that, everything is working.  Thanks.

**Comment by pawamoy** [comment]
Thanks for reporting back and closing the issue :slightly_smiling_face:
