### ISSUE TITLE
Show base class of python classes

### ISSUE THREAD

**Issue by valmar** [mkdocstrings/mkdocstrings#269]
I am testing mkdocs for the documentation of my python project and I am up until now impressed by its combination with mkdocstrings.

I was wondering if would be possible please to have the base class for derived classes displayed in the auto-generated documentation. In other words, if we have a class like:

```
class DerivedClass(BaseClass):
  pass
```
I would like to have somewhere in the documentation of DerivedClass something like: "Base class: BaseClass". I am open to any option or workaround to display this information: modifying the templates, etc.

Thank you in advance

**Comment by pawamoy** [comment]
Hello, glad to hear you enjoy this project :heart: 

It would be a nice addition indeed. This could be relatively easy to achieve in pytkdocs, by returning the parent classes (from `__mro__`) in the serialized output. They could then be rendered by mkdocstrings. We would add an option which defaults to false.
