### ISSUE TITLE
[feature request] Tabular style function documentation in the readthedocs theme

### ISSUE THREAD

**Issue by aahnik** [mkdocstrings/mkdocstrings#270]
in the material theme, we see that the arguments of a function, are laid out in a tabular style. the same should also be for readthedocs theme. it looks great.

**Comment by pawamoy** [comment]
Since it's the ReadTheDocs theme, I think it should resemble the actual ReadTheDocs theme:
![rtd](https://user-images.githubusercontent.com/3999221/114906622-830df380-9e1a-11eb-84f6-0d104c04c598.png)

So I'm kinda opposed to change it to the Material style by default. But feel free to [override some templates](https://mkdocstrings.github.io/theming/#templates) to get what you're looking for :slightly_smiling_face:

**Comment by aahnik** [comment]
in the original readthedocs, the function signature looks this this

![Screenshot from 2021-04-16 08-23-32](https://user-images.githubusercontent.com/66209958/114965731-c99d3580-9e8e-11eb-9f10-022f5803653a.png)
 
it has a nice **black text + grey background**.


but with mkdocstrings, they look like this

![Screenshot from 2021-04-16 08-32-33](https://user-images.githubusercontent.com/66209958/114965754-e0438c80-9e8e-11eb-8d34-00f211d4347a.png)

they have **orange text**

-------
hi @pawamoy,

my questions:
- how to have black text + grey background like the original readthedocs theme ?
- in the screenshot you showed in the above comment, you have  dark mode. how did you do that with mkdocs ?

**Comment by pawamoy** [comment]
Yes, our templates are not in sync with the actual ReadTheDocs theme, pull requests are welcome :slightly_smiling_face: 

> how to have black text + grey background like the original readthedocs theme ?

You'll have to override the signature template I guess, though I'm not sure how to achieve the same result as RTD. If you find a way, you can open a PR so we can better match RTD by default!

> in the screenshot you showed in the above comment, you have dark mode. how did you do that with mkdocs ?

I'm using the [DarkReader](https://darkreader.org/) browser extension :slightly_smiling_face:
