### ISSUE TITLE
Can I customize the spacing and fonts of the documentation 

### ISSUE THREAD

**Issue by UGuntupalli** [mkdocstrings/mkdocstrings#281]
Is it possible to customize the output fonts and the spacing that is rendered between functions in the documentation? I understand at this point, the theme support is limited, but within the theme, is it possible to customize the rendering? It looks a little crowded the way I currently have it generated and would love to learn how it can be toggled with different inputs to customize it. I guess the hard part is to even distinguish where a function documentation is ending and where the next one is starting even. Please see an example of what I am seeing: 

- Project Structure 

```
Project Name 
   docs 
      doc_test.md 
   src  
      doc_test.py 
``` 

- `mkdocs.yml` configuration file contents

```
site_name: Project Name
nav:
    - Home: index.md
    - About: about.md
    - Code Reference:
        - DocTest: doc_test.md
plugins:
    - search
    - mkdocstrings
theme: "material"
``` 

```
- *mkdocstrings* version: 0.15.
```

Here is my script: 
```python
from random import randrange
from importlib.metadata import version

version('mkdocstrings')


# User Inputs
length_of_list = 10
my_list = [randrange(0, 100) for x in range(0, length_of_list)]


def add_list_restructured_text_doc_style(input_list: list) -> float:
    """Calculates the sum of the items in the list

    :param input_list: items to be summed
    """
    return float(sum(input_list))


def _add_list_google_doc_style(input_list: list) -> float:
    """
    Calculates the sum of the items in the list.

    Args:
        input_list: items to be summed

    Returns:
        Sum of the elements of the list
    """
    return float(sum(input_list))
```

![ReadTheDocsExample](https://user-images.githubusercontent.com/47903157/116944573-9c8ca900-ac2a-11eb-8ccb-e7bafbe2e312.PNG)

![MaterialExample](https://user-images.githubusercontent.com/47903157/116944605-a9a99800-ac2a-11eb-930f-f3b862e6555d.PNG)

Thanks 
Uday

**Comment by oprypin** [comment]
OK for this one I have to direct you to the documentation.
https://mkdocstrings.github.io/theming/#customization
https://mkdocstrings.github.io/handlers/python/#recommended-style-readthedocs
https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
Basically you need to inspect the HTML, and rely on its elements and classes to write CSS accordingly to what you want to change.

**Comment by oprypin** [comment]
More examples:
https://github.com/mkdocstrings/mkdocstrings/pull/218/files#diff-7889a1924c66ff9318f1d81c4a3b75658d09bebf0db3b2e4023ba3e40294eb73

**Comment by UGuntupalli** [comment]
@oprypin: Oleh, Thank you for these. I don't have any knowledge about CSS, but these links should help me look through and figure where the changes should be made, so thank you for guiding me

**Comment by pawamoy** [comment]
You can typically create a CSS file somewhere in your docs directory and include it in `extra_css`:

```yaml
# mkdocs.yml
extra_css:
- css/style.css
```

Then you can use the classes listed [here](https://mkdocstrings.github.io/theming/#css-classes) to customize the fonts or many other things.

Thanks for your help @oprypin :slightly_smiling_face: 
Since the issue title was formulated as a question, and I think we answered it, I'm closing.
