### ISSUE TITLE
Pypi mkdocstrings 0.15.0 has dependency constrain `Jinja2 < 3.0`

### ISSUE THREAD

**Issue by lyz-code** [mkdocstrings/mkdocstrings#285]
I'm encountering an error when updating the dependencies of one of my projects with `pip-compile` due to the dependency constrain `Jinja2 < 3.0`.

**To Reproduce**

1. Clone the repo: `git clone https://github.com/lyz-code/mkdocs-newsletter/`
2. `cd mkdocs-newsletter`
3. Edit the first line of `docs/requirements.in` from `-r requirements.txt` to `-r ../requirements.txt`
3. `make update`

```
Could not find a version that matches jinja2<3.0,==3.0.0,>=2.10.1,>=2.11 from https://files.pythonhosted.org/packages/48/9b/dc3bbfc44d851632df958acf9d47e4de662c6bbd238e46798d555d427b27/Jinja2-3.0.0-py3-none-any.whl#sha256=2f2de5285cf37f33d33ecd4a9080b75c87cd0c1994d5a9c6df17131ea1f049c6 (from -r docs/../requirements.txt (line 56))
Tried: 2.0, 2.1, 2.1.1, 2.2, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.8, 2.8, 2.8.1, 2.8.1, 2.9, 2.9, 2.9.1, 2.9.1, 2.9.2, 2.9.2, 2.9.3, 2.9.3, 2.9.4, 2.9.4, 2.9.5, 2.9.5, 2.9.6, 2.9.6, 2.10, 2.10, 2.10.1, 2.10.1, 2.10.2, 2.10.2, 2.10.3, 2.10.3, 2.11.0, 2.11.0, 2.11.1, 2.11.1, 2.11.2, 2.11.2, 2.11.3, 2.11.3, 3.0.0, 3.0.0
Skipped pre-versions: 2.0rc1, 3.0.0a1, 3.0.0a1, 3.0.0rc1, 3.0.0rc1, 3.0.0rc2, 3.0.0rc2
There are incompatible versions in the resolved dependencies:
  jinja2==3.0.0 from https://files.pythonhosted.org/packages/48/9b/dc3bbfc44d851632df958acf9d47e4de662c6bbd238e46798d555d427b27/Jinja2-3.0.0-py3-none-any.whl#sha256=2f2de5285cf37f33d33ecd4a9080b75c87cd0c1994d5a9c6df17131ea1f049c6 (from -r docs/../requirements.txt (line 56))
  Jinja2>=2.10.1 (from mkdocs==1.1.2->-r docs/requirements.in (line 3))
  Jinja2<3.0,>=2.11 (from mkdocstrings==0.15.0->-r docs/requirements.in (line 11))
```

**Expected behavior**
`pip-compile` correctly updates the dependencies.

**Information (please complete the following information):**
- OS: Debian
- Browser: irrelevant
- `mkdocstrings` version: 0.15.0

**Additional context**

I've seen that the [pyproject.toml file](https://github.com/mkdocstrings/mkdocstrings/blob/master/pyproject.toml#L19) doesn't have that dependency, it asks for `Jinja2 < 4.0`. Maybe there was a packaging error.

**Comment by oprypin** [comment]
Already fixed in https://github.com/mkdocstrings/mkdocstrings/pull/283, not released yet (which is why you see the error but found pyproject.toml to be correct)
