### ISSUE TITLE
Intersphinx-like linking of other/remote mkdocstrings documentation

### ISSUE THREAD

**Issue by makkus** [mkdocstrings/mkdocstrings#302]
Hi there,

not quite sure whether this is a question, or a feature request, so I'll start it off as a question...

For sphinx documentation, there is [intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html), which I always found quite neat. It basically lets you easily link to other sphinx-created documentation, by configuring a prefix for that other projects documentation base url, and it'll automatically expand urls when those prefixes are found in the documentation.

Is behavior like this supported in mkdocstrings? I have a few repos that contain plugin-type classes and other elements, and it'd be cool if I could link to those from the core repo, and vice-versa. Without having to use a full url... If it is not possible now, could that be implemented, in theory?

**Comment by oprypin** [comment]
It's implemented already. https://github.com/mkdocstrings/mkdocstrings/pull/287
 But not in a release and not documented. So no worries about the request.

**Comment by makkus** [comment]
Oh, brilliant. Sorry for the noise then, didn't know what to search for :-)
