### ISSUE TITLE
lack of spaces in rendered parameter docs

### ISSUE THREAD

**Issue by brandondube** [mkdocstrings/mkdocstrings#309]
- project folder structure (`tree -L 2`)
```
.
├── LICENSE.md
├── MANIFEST.in
├── README.md
├── docs
│   ├── index.md
├── mkdocs.yml
├── prysm
│   ├── __init__.py
│   ├── _richdata.py
│   ├── bayer.py
│   ├── ...
├── setup.cfg
├── setup.py
└── tests
    ├── __init__.py
    ├── test_bayer.py
    ├── ...
 ```

- `mkdocs.yml` configuration file contents
```
site_name: prysm documentation
site_url: https://prysm.readthedocs.io/
theme: material

plugins:
  - search
  - mkdocstrings
```

- *mkdocstrings* version: [e.g. 0.10.2]
```
# Name                    Version                   Build  Channel
mkdocstrings              0.15.2             pyhd8ed1ab_0        conda-forge
pytkdocs                      0.11.1             py38h50d1736_0    conda-forge
jinja2                             3.0.1             pyhd3eb1b0_0
python                         3.8.11             h88f2d9e_1  
```

I placed an identifier in the index as a first play with mkdocs and mkdocstrings.  My code uses numpy style docstrings.  The docs source

```
::: prysm.propagation.Wavefront
    rendering:
        show_root_heading: true

```

Rendered as

<img width="764" alt="image" src="https://user-images.githubusercontent.com/13191497/130343784-a74ccae4-e73d-46c7-8162-c16331f0c5d7.png">

I expected line breaks between parameters, or the table format shown in the examples.  Did I make a mistake in the usage?  Any help is much appreciated.

**Comment by brandondube** [comment]
missed the optional dependency `pip install 'pytkdocs[numpy-style]'`

It would be useful for pytkdocs to have this as a default feature - the docstring-parser dep is only 13kB and this is a quite major feature.  (I know making it optional was explicitly part of the PR's feedback...)

<img width="764" alt="image" src="https://user-images.githubusercontent.com/13191497/130344516-ab91ed21-4329-4681-b87d-e88abdec22db.png">

**Comment by pawamoy** [comment]
> It would be useful for pytkdocs to have this as a default feature - the docstring-parser dep is only 13kB and this is a quite major feature. (I know making it optional was explicitly part of the PR's feedback...)

Sure it would be helpful for devs using the Numpy-style. But not for the others :smile:

I'm way more in favor of keeping dependencies to a minimum, or setting them as extras. Maybe we can reconsider if the Python handler is extracted from mkdocstrings and made optional as well.

**Comment by brandondube** [comment]
I think you have to pick the users you want to target and optimize for those.  Users with numpy docstrings get nothing out of google style or rst-style docstrings and still have to have the machinery for those installed.  Since there isn't a de-facto way to write docstrings in python, I guess you have to pick your favorite kid and forget the rest (hide them in optional installs).

At the least, I would suggest adding the syntax for the optional installs to the installation part of the docs.

I think breaking out the primary "driver" and making it an optional dependency is very, very much not a good design decision -- I'm more willing than most users to dig into problems and find root cause (most would just turn away instead of spending > 1 hr figuring out how to make numpy-style docstrings work).  If this python targeting docs tool "didn't work" from basic installation because an optional dependency would needed, I would look elsewhere and never look back - that's a dead on arrival level of broken.

**Comment by pawamoy** [comment]
> At the least, I would suggest adding the syntax for the optional installs to the installation part of the docs.

You are totally right, the docs have been improved since then but were not deployed yet. Sorry this was so troublesome to setup.

About a favorite kid: mine is Google. So it was the first style supported, and therefore is still the default. Google and RST styles are implemented without any additional dependencies, that's why they are natively available. A PR implementing Numpy-style parsing without any additional dependency would be welcome :slightly_smiling_face: 

As for Numpy-style being the "primary" driver: we should probably get the numbers to proove that. I witnessed a certain amount of data-science oriented projects using mkdocstrings on GitHub, true, though didn't check the docstring style they use. I myself see Google-style more often than any other style, at least in the projects I contribute too. We are probably both biased towards a particular style.

**Comment by brandondube** [comment]
I guess I just.......don't understand your viewpoint.  _Why the hard line on this dependency?_  It's not like the author of that PR pulled in Boost or opencv or some other behemoth that makes things unwieldly.

It demotivates me as a user to see apparent arbitrary top-down rules that spawn hours of debugging for prospective users of this tool when trying to use it to process an extremely common docstring format.

**Comment by pawamoy** [comment]
Again, sorry you spent hours debugging this. The next version of the docs will make it clear that you need the `numpy-style` extra. Maybe this could be set as an extra on mkdocstrings as well. If it is well documented, I don't see how that's a problem for users.
