### ISSUE TITLE
Ability to link object types

### ISSUE THREAD

**Issue by LordOfPolls** [mkdocstrings/mkdocstrings#317]
**Is your feature request related to a problem? Please describe.**
Unable to create a link inside parameters docstring

**Describe the solution you'd like**
I woiuld like the ability to link my parameters object types to their definition. Ie the user can click on the parameter's type field, and be taken to my definition of said type

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pawamoy** [comment]
Hello @LordOfPolls, thank you for the feature request :slightly_smiling_face: 
I'm currently prototyping a better data extractor to replace pytkdocs, which is quite limited by its design (loading and introspecting code). The ability to link object types is definitely planned for mkdocstrings and the new extractor.

**Comment by LordOfPolls** [comment]
Awesome. Appreciate the hard work.

I don't suppose there's an ETA on thst? Or is it too soon to say?

**Comment by pawamoy** [comment]
Hmmm, it's progressing well, and maybe I'll be able to release a beta in something like a month, but it will probably not have feature parity with pytkdocs.

**Comment by LordOfPolls** [comment]
Thanks a lot, ill keep an eye out for that release

**Comment by LordOfPolls** [comment]
Any update on this?

**Comment by pawamoy** [comment]
My previous ETA for a beta was pretty optimisitc 😅 But yeah, updates: the data extractor (griffe) is almost ready (namespace package support turns out to be quite complicated) for wild beta-testing. Just one or two PR to merge into mkdocstrings and you'll be able to try it (with git installs). A few more PRs and releases and you'll be able to depend on everything with `mkdocstrings[python]` 🙂 

Then the extractor will need some refining for cases where simply visiting the AST is not enough and hybrid visit+inspection is required. But it's already nicely laid out.

**Comment by pawamoy** [comment]
Now available! See https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers
Automatic cross-refs for every annotations :drooling_face: :rocket: :heart: :star:

**Comment by LordOfPolls** [comment]
Unforuntately it appears the new handler can't read my codebase. So far i've come accross 2 issues that im unsure if are caused by issues in my codebase, or with the new handler. 

- `loader.py`:282 - charmap cant decode character.
  - Resolved by changing line to `code = module_path.read_text("utf-8")`
- `rendering.py`: 109 - TypeError: '<' not supported between instances of 'NoneType' and 'int'

I'm unsure if these are being caused by Griffe, mkdocstrings, or my codebase, so im unsure where i'd even put an issue.

**Comment by pawamoy** [comment]
Your codebase is most certainly fine, Griffe probably does not support every kind of AST node / combination of nodes.
Could you check though that your modules triggering the encoding issue are UTF8 encoded?
The type error is weird: there are literally no `<` comparison in mkdocstrings' rendering module.
I'll need a longer traceback :smile: You can open a new issue here on mkdocstrings repository. Please provide the versions of mkdocstrings, mkdocstrings-python and griffe.

Also, thanks for the report :slightly_smiling_face:

**Comment by LordOfPolls** [comment]
I've created an issue, with full tracebacks 😉
