### ISSUE TITLE
Support "Yields" in docstrings

### ISSUE THREAD

**Issue by nina-j** [mkdocstrings/mkdocstrings#324]
**Is your feature request related to a problem? Please describe.**
Per the [Google styleguide](https://google.github.io/styleguide/pyguide.html#doc-function-returns), the keyword `Yields` is used for generators. However, when using `Yields` in a docstring, it is not parsed by `mkdocstrings`:

![image](https://user-images.githubusercontent.com/28903001/135604499-e86d9a00-a049-4be4-9c5a-b91545f54e56.png)

**Describe the solution you'd like**
I'd like `Yields` to be parsed in the same manner that `Returns` is. :)

**Comment by pawamoy** [comment]
Coming with pytkdocs 0.13: https://github.com/mkdocstrings/pytkdocs/pull/116
We'll have to update the templates on mkdocstrings side.

**Comment by nina-j** [comment]
Awesome, thanks!

**Comment by 1081** [comment]
Perfect! Please also include the other missing "Keywords":
- Notes
- Todo
- Raises
