### ISSUE TITLE
Support  pymdown-extensions version 9.0

### ISSUE THREAD

**Issue by athackst** [mkdocstrings/mkdocstrings#325]
pymdown-extensions is now at version 9.0 

see [release notes](https://github.com/facelessuser/pymdown-extensions/releases/tag/9.0)

It would be great if the prereqs included support for this version.  Is there anything release-blocking in the notes that would prevent that?

https://github.com/mkdocstrings/mkdocstrings/blob/ecc80b329206d535398edbc065ab7d872318e665/pyproject.toml#L26

**Comment by pawamoy** [comment]
Based on the release notes, I think we can update the accepted range of versions to contain 9.0, yes :slightly_smiling_face:

**Comment by camold** [comment]
The current versions of mkdocs-material (7.3.1) and mkdocstrings (0.16.1) are conflicting on pip, since
mkdocstrings requires pymdown-extensions < 9.0, and mkdocs-material requires >= 9.0.

**Comment by pawamoy** [comment]
Just merged #327, will now release 0.16.2.
