### ISSUE TITLE
Add ability to order properties before signature

### ISSUE THREAD

**Issue by Bluenix2** [mkdocstrings/mkdocstrings#326]
**Describe the solution you'd like**
I would like to order `async`, `property`, `classmethod` and similar properties *before* the name of the function.

**Describe alternatives you've considered**
I've been playing around with custom CSS to get it to work, but utlimately failed.

**Additional context**
If needed I could implement this myself, I would just like some pointers to appropriate files and methods to look at in rough terms.

**Comment by pawamoy** [comment]
Hello! I think you can achieve that using [custom templates](https://mkdocstrings.github.io/theming/#templates). The issue is that properties are added _after_ the name in every object template (attribute, function, class, etc.), so you'd have to override each one of them and it would feel wasteful :confused: We need a better template inheritance and overriding system.

Other than that, it looks like it could be done with CSS: https://stackoverflow.com/a/26113333/3451029

**Comment by Bluenix2** [comment]
> Other than that, it looks like it could be done with CSS: https://stackoverflow.com/a/26113333/3451029

Yes this is what I tried, but I am not the best with CSS and the result became this:
![image](https://user-images.githubusercontent.com/38372706/135753981-b8d21b60-28bd-475a-91a8-1e25df057120.png)

I'll take a look at custom templates thank you.

**Comment by Bluenix2** [comment]
Here is the final custom template, thanks for all your help!

```jinja2
{{ log.debug() }}
{% if config.show_if_no_docstring or method.has_contents %}

  <div class="doc doc-object doc-method">
  {% with html_id = method.path %}

    {% if not root or config.show_root_heading %}

      {% if root %}
        {% set show_full_path = config.show_root_full_path %}
        {% set root_members = True %}
      {% elif root_members %}
        {% set show_full_path = config.show_root_members_full_path or config.show_object_full_path %}
        {% set root_members = False %}
      {% else %}
        {% set show_full_path = config.show_object_full_path %}
      {% endif %}

      {% filter heading(heading_level,
          role="method",
          id=html_id,
          class="doc doc-heading",
          toc_label=method.name ~ "()") %}

        <!-- Here is what's changed. We order properties before the signature -->
        {% with properties = method.properties %}
          {% include "properties.html" with context %}
        {% endwith %}

        {% filter highlight(language="python", inline=True) %}
          {% if show_full_path %}{{ method.path }}{% else %}{{ method.name }}{% endif %}
          {% with signature = method.signature %}{% include "signature.html" with context %}{% endwith %}
        {% endfilter %}

      {% endfilter %}

    {% else %}
      {% if config.show_root_toc_entry %}
        {% filter heading(heading_level,
            role="method",
            id=html_id,
            toc_label=method.path,
            hidden=True) %}
        {% endfilter %}
      {% endif %}
      {% set heading_level = heading_level - 1 %}
    {% endif %}

    <div class="doc doc-contents {% if root %}first{% endif %}">
      {% with docstring_sections = method.docstring_sections %}
        {% include "docstring.html" with context %}
      {% endwith %}

      {% if config.show_source and method.source %}
        <details class="quote">
          <summary>Source code in <code>{{ method.relative_file_path }}</code></summary>
          {{ method.source.code|highlight(language="python", linestart=method.source.line_start, linenums=False) }}
        </details>
      {% endif %}
    </div>

  {% endwith %}
  </div>

{% endif %}
```
