### ISSUE TITLE
Roadmap for mkdocstrings/pytkdocs in regard to extensions

### ISSUE THREAD

**Issue by mansenfranzen** [mkdocstrings/mkdocstrings#332]
Hi  @pawamoy,

Thanks a lot for creating `mkdocstrings` and `pytkdocs`! It's great to see the rise of auto-documentation with mkdocs, too.

### Background

I've been mainly using sphinx in the past but I start to see a great benefit in using mkdocs and your packages because of simplicity and ease of development. Sphinx' code base is huge and has a lots of complexity. 

I've recently created the [autodoc_pydantic](https://github.com/mansenfranzen/autodoc_pydantic) sphinx extension to allow proper automated documentation for pydantic models/settings. I'm thinking about adding support for mkdocstrings, too. In fact, I would really like to.

### Problem description 

However, I've come across some issues while experimenting with pytkdocs in regard to pydantic models which are currently a stopper for me:

- default values for class attributes (aka fields) are not fetched
- root validators are not picked up
- standard doc strings for fields are not collected (currently the field description is used instead)

I can see two possible approaches to tackle these points:

1. Adjust pytkdocs' code base to support custom pydantic requirements.
2. Allow extensions to handle introspection for custom classes much like sphinx.ext.autodoc offers.

The former approach works on short term (as it already partially does for pydantic). However, I guess it's not the best solution on long term because all logic about custom types is entangled in pytkdocs' core. There are more use cases other than pydantic which would require the same treatment and ultimately they would all need to go in pytkdocs's core.

The latter approach seems much more flexible because it would allow external developers to extend pytkdocs' core to support custom types. Hence, pytkdocs remains lean and supports the python defaults only while offering an interface to register custom *collectors*. This is currently possible with `sphinx.ext.autodoc` which is really great. I would love to see the same with pytkdocs.

There might be a third approach to completely bypass pytkdocs but this would mean duplicating lots of functionality. I don't consider this viable.

### Question

I scanned through some of the existing issues which also touch this topic. I'm interested to know where you're currently heading and what your roadmap looks like.

Thanks!

**Comment by mansenfranzen** [comment]
Thanks for your roadmap and clarification. I can totally understand that you stop investing your main efforts in pytkdocs due to the issues you've mentioned. Since it's open source and it's your time, focus on whatever makes you happy :-). 

I don't feel capable adding an extension system to pytkdocs. I also feel that this would be wasted effort if pytkdocs is going to be deprecated sooner or later.

Sphinx uses introspection via loading python objects into memory during the doc generating process ([see here for example](https://github.com/sphinx-doc/sphinx/blob/56f97d71a2b1733ebf401d357a634e2d7e4c896e/sphinx/ext/autodoc/__init__.py#L425)). There is no subprocess involved. Everything happens in the same python process. 

I am by no means an expert on this but I found the introspection approach to be very useful and intuitive. It allows to *observe* the objects the way they *appear* during runtime. In my opinion this is an advantage. Due to python's dynamic nature, objects can be completely modified during runtime via metaclasses or decorators. When parsed *statically* from source code (and not being importing directly), I wonder how it's possible to know about such modifications (perhaps that's just due to my lack of understandig and please tell me otherwise).

In my opinion, the ideal doc generating framework should natively support both approaches. If statically parsed code is sufficient, just rely on that. If you need introspection, make it easily available. The developer creating the extension should have the choice.

Regarding the performance issue you've mentioned with introspection, I haven't come across the situation that the doc building process took too long. It's often slow, I have to admit, but it is not a real bottleneck that needs a paradigm shift to be fixed. Building docs isn't a critical process that runs 24/7 which would cause lots of CPU hours to pay for (at least not in the settings I'm familiar with). Hence, the convenience and ease of use that introspection provides outweights the performance penalty by far.

I will take a closer look at griffe and give it a shot adding an experimental extension for pydantic. I'm curious to see how the parsing approach differs in outcome and developer experience.

**Comment by pawamoy** [comment]
Hey @mansenfranzen, I ended up implementing your suggestion of having both visiting and introspecting methods to load data :smile: It's still very raw but I've wrote a prototype of an extension allowing hybrid behavior: inspect some kinds of objects while visiting the tree.

It allows to write something like this:

```python
# my_pacakge.my_extension.py
from __future__ import annotations

from griffe.agents.extensions.base import InspectorExtension, When
from griffe.agents.nodes import ObjectNode


class MyExtension(InspectorExtension):
    when = When.after_all

    def __init__(self, **options) -> None:
        super().__init__()
        # do something with options

    def inspect_class(self, node: ObjectNode) -> None:
        # access object with node.obj
        # access data parent with self.visitor.current
        # etc.

# make it visible to Griffe
Extension = MyExtension
```

...and, in theory (this part is not implemented yet):

```yaml
# mkdocs.yml
plugins:
  mkdocstrings:
    handlers:
      python:
        extensions:
        - hybrid:
            extension:
              my_package.my_extension:
                option: value
```

**Comment by pawamoy** [comment]
New handler available, extensions system implemented in the new data collector: https://mkdocstrings.github.io/griffe/
The extensions system is really not mature though. I'll document it better and progressively improve it. Feedback would be welcome!
