### ISSUE TITLE
Author's Website link returns 404

### ISSUE THREAD

**Issue by johnthagen** [mkdocstrings/mkdocstrings#337]
**Describe the bug**

Opening the "Author's Website" tab in the user guide returns a 404.

**To Reproduce**

1. Open hosted user guide
2. Select Author's Website ( https://mkdocstrings.github.io/pawamoy.github.io)

<img width="504" alt="Screenshot 2021-10-17 141740" src="https://user-images.githubusercontent.com/10340167/137639856-c8ee8417-a62a-4c9c-913d-63a7bd66c194.png">

**Comment by johnthagen** [comment]
This also happens to the crystal handler external link. Perhaps it's the way the docs are hosted on GitHub Pages?

**Comment by pawamoy** [comment]
Resolved with mkdocs-literate-nav 0.4.1 (thanks @oprypin), thanks again for the report @johnthagen :slightly_smiling_face:
