### ISSUE TITLE
Compatibility with mkdocs-material>=7.3.1

### ISSUE THREAD

**Issue by mondeja** [mkdocstrings/mkdocstrings#344]
**Describe the bug**

mkdocstrings is not compatible with mkdocs-material starting at v7.3.1, because has pinned pydown-extensions to `>=9.0.0`.
See [this release diff](https://github.com/squidfunk/mkdocs-material/compare/7.3.0...7.3.1#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L25).

<details>
  <summary>Traceback</summary>

```
mkdocs-material 7.3.6 depends on pymdown-extensions>=9.0
mkdocstrings 0.15.2 depends on pymdown-extensions<9.0 and >=6.3
```

</details>

**Comment by pawamoy** [comment]
You have to upgrade to mkdocstrings >= 0.16, it supports pymdown-extensions >= 9.0 :slightly_smiling_face:

**Comment by mondeja** [comment]
Great, thank you!
