### ISSUE TITLE
Nested autodoc (autodoc in docstrings) breaks nav

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#348]
```python
class GriffeLoader(_BaseGriffeLoader):
    """The Griffe loader, allowing to load data from modules.

    ::: griffe.loader._BaseGriffeLoader.__init__
    """
```

Every item rendered before `::: griffe.loader._BaseGriffeLoader.__init__` (including it) is lost: they do not appear in the nav (secondary nav? the right sidebar by default on Material).

Without nested autodoc | With nested autodoc
--- | ---
![notnested](https://user-images.githubusercontent.com/3999221/142912337-78ad87b7-9550-460d-8ad7-db2339e8e48b.png) | ![nested](https://user-images.githubusercontent.com/3999221/142912353-dfbf1028-8470-4671-be23-ac876335393d.png)

**Information (please complete the following information):**
- OS: arch
- Browser: firefox
- `mkdocstrings` version: 0.16.2

**Additional context**
Probably related to autorefs.

## Boost priority

- Boost priority in our backlog through [Polar.sh](https://polar.sh/pawamoy). Higher pledge, higher priority.
- Minimum pledge by user/organization is $5, minimum amount for boost is $30. 
- View [all issues with pledges](https://polar.sh/pawamoy/issues?sort=most_funded&badged=1).
- We receive the funds once the issue is completed and confirmed by you.
- Features with the [insiders](../labels/insiders) label are released to sponsors first, and tied to a [funding goal](https://pawamoy.github.io/insiders/#funding).

<a href="https://polar.sh/mkdocstrings/mkdocstrings/issues/348">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/mkdocstrings/mkdocstrings/issues/348/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/mkdocstrings/mkdocstrings/issues/348/pledge.svg">
</picture>
</a>

**Comment by waza-ari** [comment]
I know this issue is quite old, but I'm seeing the same behavior even in today's version `0.24.0`. I guess that feature is not commonly used.

In the content area, the nested autodoc is rendered correctly (including the correct heading levels), but in the Nav is broken, just as explained.

Any idea what could be causing this issue?

**Comment by pawamoy** [comment]
Indeed, the issue is not fixed yet, and I believe very few try to nest autodoc in docstrings.

For a possible explanation: it's possible that the nested rendering pass breaks the context/state of the upper pass, notably the headings recorded by the `toc` extension. This issue might be magically fixed if we move to a [`pymdownx.blocks`](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/) implementation of the extension instead of `:::` markup.

**Comment by pawamoy** [comment]
Might be able to fix this by setting a `nested` variable in the handler to true in the `try` block of `do_convert_markdown`, and restore its previous value in `finally`. Then by updating `AutodocProcessor.run` to reassign headings (`handler._headings`) when in "nested" mode (to propagate them back to the upper layer) and optionally drop the headings logic when "nested".
