### ISSUE TITLE
Support latest version of pytkdocs

### ISSUE THREAD

**Issue by lyz-code** [mkdocstrings/mkdocstrings#351]
**Describe the bug**
Latest version of mkdocstrings `0.16.2` has a pin on `pytkdocs` of `>=0.2.0,<0.13.0`

```bash
$: poetry show mkdocstrings
name         : mkdocstrings
version      : 0.16.2
description  : Automatic documentation from sources, for MkDocs.

dependencies
 - Jinja2 >=2.11.1,<4.0
 - Markdown >=3.3,<4.0
 - MarkupSafe >=1.1,<3.0
 - mkdocs >=1.2,<2.0
 - mkdocs-autorefs >=0.1,<0.4
 - pymdown-extensions >=6.3,<10.0
 - pytkdocs >=0.2.0,<0.13.0
```

The latest version of `pytkdocs` is `0.14.0`

**To Reproduce**

* `poetry add mkdocstrings`

**Expected behavior**

`pytkdocs` version `0.14.0` is installed

**Information (please complete the following information):**
Irrelevant

**Comment by pawamoy** [comment]
Yup, and based on this article https://iscinumpy.dev/post/bound-version-constraints/ we should probably get rid of all these upper bounds, unless we have one of the reasons mentioned in the article to keep some.

**Comment by pawamoy** [comment]
Done in #153. Waiting for a possible review, then I'll publish a new release.
