### ISSUE TITLE
Python functions collected and found but no documentation rendered. 

### ISSUE THREAD

**Issue by duncaneddy** [mkdocstrings/mkdocstrings#357]
First, let me say thank you for building and maintaining this software — super excited it exists!

**Please open an issue on [pytkdocs](https://github.com/pawamoy/pytkdocs/issues) instead
if this is related to Python docstrings parsing or the collection of Python objects!**

I believe this is the right bug location since it related to rendering of the docstrings, the collection appears to be working as expected.

**Describe the bug**
I am currently working on a project that is a Rust crate with a paired python-wrapper, jointly built and compiled at the same time. I am working on adding API reference documentation for the python interface using mkdocstrongs.

The issue is that despite the module being found on the Python path, doctoring being present and in the correct format, and documentation compiling, nothing renders. This can be seen on the hosted documentation page [here](https://duncaneddy.github.io/rastro/python_api/orbits/#rastro_python.orbits.orbital_period)

I have followed the instructions on the [troubleshooting](https://mkdocstrings.github.io/troubleshooting/#nothing-is-rendered-at-all) page and that did not resolve the issue.

**To Reproduce**

To reproduce you can setup the development environment locally and compile the documentation. Alternatively you can inspect the [resulting webpage]((https://duncaneddy.github.io/rastro/python_api/orbits/#rastro_python.orbits.orbital_period)) or submit a pull request for the [repository](https://github.com/duncaneddy/rastro).
1. Clone the repository locally
2. [Install Rust](https://www.rust-lang.org/tools/install)
3. Setup a local [Python 3.6+ virtual environment](https://towardsdatascience.com/python-how-to-create-a-clean-learning-environment-with-pyenv-pyenv-virtualenv-pipx-ed17fbd9b790)
4. Build the python package and install documentation dependencies with `./docs/build.sh install`
5. Build and serve the documentation locally `./docs/build.sh`
6. Navigate to the expected API reference page (./rastro/python_api/orbits) and notice that the expected API documentation is not visible, however Table of Contents displays the expected function name.

**Expected behavior**

I would expect given the current setup that docstrings would be properly generated and displayed correctly at the [API reference documentation page](https://duncaneddy.github.io/rastro/python_api/orbits/#rastro_python.orbits.orbital_period). Before submitted this bug report I have confirmed that the module is discoverable and the python module functions contain the properly formatted docstrings. The associated documentation page generating this specific reference API page is [here](https://github.com/duncaneddy/rastro/blob/main/docs/en/docs/python_api/orbits.md).

First, I have confirmed that the module is being properly discovered an imported. This is confirmed by virtue of the documentation compiling. I have attempted to change the documentation markup `::: rastro.orbital_period` to other values such as `::: rastro_python.orbital_period` which cause compilation errors. Additionally, in the same python environment you can confirm that the module is present by simply running:

```python
import rastro
```

Next I confirmed that the docstrings are properly present in the module by importing the module and attempting to print the docstring:

```python
import rastro
print(rastro.orbital_period.__doc__)
```

This will display the expected docstring in Google-style format.

At this point, I'm not sure why, given the module is present, the docstrings are present, and mkdocstrings parses the module and generates the section that the API reference is not displaying. I have also run `MkDocs` in verbose mode with `mkdocs serve -v` which shows the `mkdocstrings` running and parsing the module successfully.

I'm happy to continue to investigate more but am not sure what threads to pull at this point. My one thought is that the table of contents shows the function name as `rastro_python.orbital_period` while the module name is `rastro` for the import and all function calls. I'm wondering if there is not some strange artifact being introduced from the pathing artifacts of the dual, Rust-Python, package setup that causes some auto-discovery process to fail.

Any advice in how to track this down would be much appreciated! Thank you.

**Screenshots**
N/A see links.

**Information (please complete the following information):**
- OS: MacOS 12.1
- Browser: Safari and Firefox
- `mkdocstrings` version: 0.17.0
- Python 3.8.12
- Rust 1.57.0

**Additional context**

See **Expected Behavior**

**Comment by pawamoy** [comment]
Hi, thank you very much for the highly detailed report! I'll try to replicate tomorrow, but from a quick glance, I'd say you're right and there's a mismatch somewhere, probably around the parent module of your rastro objects.

**Comment by duncaneddy** [comment]
Much appreciated and no rush!

**Comment by pawamoy** [comment]
Step 4 fails :confused: 

```console
% ./docs/build.sh install
Install rastro pyhton
Processing ./rastro_python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: rastro
  Building wheel for rastro (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /media/data/dev/rastro/.venv/bin/python3.7 /media/data/dev/rastro/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpkzj9kjg3
       cwd: /tmp/pip-req-build-26cvj0zm
  Complete output (80 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/rastro
  copying rastro/__init__.py -> build/lib.linux-x86_64-3.7/rastro
  running egg_info
  writing manifest file 'rastro.egg-info/SOURCES.txt'
  running build_ext
      Updating crates.io index
  error: failed to get `rastro` as a dependency of package `rastro_python v0.0.0 (/tmp/pip-req-build-26cvj0zm)`
  
  Caused by:
    failed to load source for dependency `rastro`
  
  Caused by:
    Unable to update /tmp/rastro
  
  Caused by:
    failed to read `/tmp/rastro/Cargo.toml`
  
  Caused by:
    No such file or directory (os error 2)
  Traceback (most recent call last):
    File "/media/data/dev/rastro/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/media/data/dev/rastro/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/media/data/dev/rastro/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 29, in <module>
      long_description_content_type='text/markdown',
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools_rust/setuptools_ext.py", line 132, in run
      build_rust.run()
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools_rust/command.py", line 101, in run
      self.run_for_extension(ext)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools_rust/build.py", line 108, in run_for_extension
      dylib_paths = self.build_extension(ext, self.target)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools_rust/build.py", line 139, in build_extension
      target_dir = _base_cargo_target_dir(ext)
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools_rust/build.py", line 673, in _base_cargo_target_dir
      target_directory = ext._metadata()["target_directory"]
    File "/tmp/pip-build-env-4xko29rk/overlay/lib/python3.7/site-packages/setuptools_rust/extension.py", line 200, in _metadata
      self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.7.12/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
  ----------------------------------------
  ERROR: Failed building wheel for rastro
Failed to build rastro
ERROR: Could not build wheels for rastro which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/media/data/dev/rastro/.venv/bin/python3.7 -m pip install --upgrade pip' command.
```

**Comment by pawamoy** [comment]
Some progress: it works better without build isolation: `pip install setuptools_rust; cd rastro_python; python setup.py install`
New error:

```
Running `/media/data/dev/rastro/target/release/build/rsofa-d761c8c1fe18380d/build-script-build`
error: failed to run custom build command for `rsofa v0.4.5`

Caused by:
  process didn't exit successfully: `/media/data/dev/rastro/target/release/build/rsofa-d761c8c1fe18380d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/pawamoy/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
error: cargo failed with code: 101
```

**Comment by duncaneddy** [comment]
😕 Let me look into this and update you. Apologies for this not working out of the box.

Ah! Just saw the update. Much appreciated. Looks like I also have some improvement to do of the build process overall.

**Comment by pawamoy** [comment]
OK, just had to install clang (`sudo pacman -S clang`).

So! I ran some tests. Basically, compiled stuff ("built-in" stuff according to Python) is not well supported :sweat_smile: 
The data extractor (pytkdocs) assumes certain things like "the module has a filepath" and else, which generate TypeErrors (which are not caught in the current version). I'll see if this can be fixed easily (hoping these assumptions do not contaminate the whole code base).

The improved data extractor I've been working on (griffe) already works better, though the `orbital_period` member is not properly detected as a function: 

```python
>>> from griffe.agents.inspector import inspect
>>> rastro = inspect("rastro")
>>> rastro["orbital_period"].kind
<Kind.ATTRIBUTE: 'attribute'>
```

The kind detection comes directly from pytkdocs: https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/loader.py#L121 and siblings. There's lot of room for improvement I guess :slightly_smiling_face: 
I'm currently working on releasing experimental use of griffe through a new mkdocstrings Python handler, I'll let you know when it's ready to beta-test (it would help a lot if you beta-test it!).

Another thing probably worth noting. Your rastro modules does a `from rastro_python.orbits import *`:

- wildcard imports are considered bad-practice (and I realize that you might not have control over this), and are not well supported by pytkdocs/griffe
- in your package, the `orbital_period` function is *publicly exposed* as `rastro.orbital_period`, but pytkdocs does not support this and always tries to get the original module the object comes from, in this case `rastro_python`, which explains the anchor in the ToC. More issues arises from this lack of support for *public* paths (not trivial to support :smile: griffe *does* support it now, but not pytkdocs).

There's a last thing that breaks pytkdocs as well: it seems your package contains the `setup.py` script as a submodule! When pytkdocs discovers submodules, it then tries to import this `setup` module and ends up triggering the installation process, which in turn raises a SystemExit (process exits). You can fix this on your end by either preventing inclusion of `setup.py` into your final package (I don't know how you'd do that), or by preventing accidental execution of the installation process by protecting the `setup()` call under a condition:

```python
if __name__ == "__main__":
    setup(...)
```

---

I've wrote about quite a number of things so don't hesitate to ask details if something wasn't clear!

**Comment by duncaneddy** [comment]
This is great—thank you for taking the time to dig into this and write such a helpful response with improvements on multiple fronts!

Definitely happy to help beta test your new griffe data extractor whenever you think it's ready! Just let me know and I'll try it out and start using it. This isn't an urgent issue for me to resolve since I still have plenty to develop to get rastro out of early development itself. I'm just appreciative of your work on good tools to auto-generate good documentation 😀 It makes such a difference for usability.

I'll fix the wildcard imports, I believe that was holdover of laziness on my part when I first trying to see such a dual-package could work. Also good to know about `setup.py` being included in the package distribution. I'll add the guard for to prevent accidental execution of installation on import definitely seems like the best fix for now. 

Appreciate the explanation of public exposure vs the module path. I'm super glad giffe does support the difference because I honestly don't know how I would be able to fix the package naming conflict otherwise. Since in this simultaneous built setup `rastro` is already taken by the base Rust package. 

I'm good to consider this issue closed for now. Please let me know when you'd like beta testers for griffe, more than happy to try it out!

**Comment by pawamoy** [comment]
Your project was very useful to me, to bring support for non-standard built-in modules in griffe :smile: Thanks!
Also, your setup.py script is not actually included in the "final package" as I stated before, it's just that I happened to run Python in the repository root, and Python would find `rastro_python` in the current directory (common issue with Python, some of us like to use an "src layout" to prevent that).

So, griffe now supports .so files (and .pyc, .pyo and .pyd files as well). Next thing would be to support wildcard imports when visiting a module (visiting its AST). This is going well :smile:

**Comment by duncaneddy** [comment]
That's awesome to hear!

My development has slowed down now that the holidays are over, but I'm hoping to push an update in the next couple of weeks that will hopefully have two effects:
1. I've found some better ways to use the Rust bindings library that will hopefully build the package in a more Python-friendly way for better discovery. (Though this may not be entirely helpful for your purposes of having a non-standard module test case).
2. I'll be adding some more complicated bindings that will add classes with attributes and methods to the system which may provide some more interesting test cases for non-standard support.

**Comment by pawamoy** [comment]
> Though this may not be entirely helpful for your purposes of having a non-standard module test case

That's fine, I think griffe now catches 99% of errors that can be raised. Making your package more inspect-friendly is the right thing to do.

> I'll be adding some more complicated bindings that will add classes with attributes and methods to the system which may provide some more interesting test cases for non-standard support.

Great, let me know when I can put this to test :slightly_smiling_face:

**Comment by pawamoy** [comment]
The [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers) is available so I believe we can close this :slightly_smiling_face:
