### ISSUE TITLE
Full usage instructions not showing on your webpage

### ISSUE THREAD

**Issue by EqualAPriori** [mkdocstrings/mkdocstrings#362]
The sidebar for "usage" looks like:
![image](https://user-images.githubusercontent.com/16579314/149600181-fd24f3e8-483b-4322-a77a-cfe88939dd58.png)

Whereas, when looking at the `nav` of the `mkdocs.yml` there are clearly many more sections expected under usage: 
![image](https://user-images.githubusercontent.com/16579314/149600298-cb64118f-a021-49d6-a204-c5e894244b00.png)

I can view those pages by navigating through the repository, but I imagine you probably want them to show up on the webpage as well/

**Comment by pawamoy** [comment]
Thanks, fixed now!
