### ISSUE TITLE
Better rendering of Types and Defaults

### ISSUE THREAD

**Issue by LordOfPolls** [mkdocstrings/mkdocstrings#363]
**Is your feature request related to a problem? Please describe.**
Currently, this library will show the full path of any non-builtin Type Annotations. This often causes the description section to be *squished* and making the docs less desirable to read. 
As well as this, default values are `repr`ed rather than just disaplying their name, for large objects like IntFlags, this can make the documentation even harder to read. 
Couple both of these issues and you have some **very** messy docs.

Here is an example from your own docs. 

Currently:
![image](https://user-images.githubusercontent.com/22540825/149731548-0248567c-7dbd-4fe7-8527-a17f023cf123.png)
Desired:
![image](https://user-images.githubusercontent.com/22540825/149731636-24270fc7-2814-49f3-8654-531fda056453.png)

From my own docs, here is a worst case example of a Type Annotation displaying its full path, plus this library `repr`ing the default
![image](https://user-images.githubusercontent.com/22540825/149732533-2a7d4684-5c72-4dc2-b53d-e3953b27eccc.png)
As you can see `description` gets squished to the point it may as well not be there

**Describe the solution you'd like**
An option to **only** display the name of the Type, not its path. And another option to not `repr` the default value, and instead show its name

**Describe alternatives you've considered**
I have tried writing the type in my docstrings, hoping this library would use that, however it will ignore that and use my type annotations instead.

**Comment by pawamoy** [comment]
Hey! Totally agree :slightly_smiling_face: 

Let me give you a glimpse of the new handler capabilities:

Table style:
![griffe_param_table](https://user-images.githubusercontent.com/3999221/149814403-c2887266-2b4b-493f-b345-155abb19bfaf.png)

SpaCy style:
![griffe_param_spacy](https://user-images.githubusercontent.com/3999221/149814406-a7b7fc90-3d44-4d99-a9ef-7a2da5459751.png)

List style (default not displayed yet, not sure how we should display it):
![griffe_param_list](https://user-images.githubusercontent.com/3999221/149814409-7b52602a-ad8b-45f2-834e-fbe7053bcfdb.png)

Types are rendered as written in the source. Ideally defaults will automatically cross-reference objects as well.
If type and default are squishing the description too much, the spacy style can help. The least problematic style will always be the list one.

What do you think?

**Comment by LordOfPolls** [comment]
This makes me very happy. I think most of my pestering will be solved once we get that handler 😅

**Comment by pawamoy** [comment]
New handler is here! https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers
I would greatly appreciate if you could give it a try @LordOfPolls, even if you don't adopt it (as it's still experimental) and just report back some issues :slightly_smiling_face: 
I'll close this for now as I'll likely *not* work on the legacy handler anymore, but feel free to further comment or reopen :slightly_smiling_face:
