### ISSUE TITLE
Specifying where to render module docstrings

### ISSUE THREAD

**Issue by davidorme** [mkdocstrings/mkdocstrings#372]
Hi,

`mkdocstrings==0.13.6`

I have a module that contains some classes, some convenience functions and some global Logger objects and I'm trying to keep these in separate sections in a page. So, I have markdown file containing:

```md
## Custom logging classes

::: safedata_validator.logger
    rendering:
        show_source: true
    selection:
        members:
            - CounterHandler
            - IndentFormatter      

## Global logging instances

::: safedata_validator.logger
    rendering:
        show_source: true
    selection:
        members:
            - CH
            - CONSOLE_LOG
            - LOG
            - FORMATTER
```

My problem is that all of the blocks also include the rendered contents of the _module_ docstring. Ideally I'd like to have that by itself at the top of the file as an introduction and then for it not to appear anywhere else. I can't see any obvious setting for this.

**Comment by pawamoy** [comment]
Try this:

```md
## Custom logging classes

::: safedata_validator.logger.CounterHandler
::: safedata_validator.logger.IndentFormatter

## Global logging instances

::: safedata_validator.logger.CounterHandler.CH
::: safedata_validator.logger.CounterHandler.CONSOLE_LOG
::: safedata_validator.logger.CounterHandler.LOG
::: safedata_validator.logger.CounterHandler.FORMATTER
```

**Comment by davidorme** [comment]
Thanks for the really quick reply @pawamoy. That does do the trick. The only modification I made was to add the root heading back in for element so that the object name appears as a subheading.

```md
## Custom logging classes

::: safedata_validator.logger.CounterHandler
    rendering:
        show_root_heading: True
::: safedata_validator.logger.IndentFormatter
    rendering:
        show_root_heading: True
```

**Comment by pawamoy** [comment]
You're welcome! Thank you for reporting back :slightly_smiling_face: 
I believe this issue can be closed now!
