### ISSUE TITLE
Ignore the checking of static files when building

### ISSUE THREAD

**Issue by OllieBroadhurst** [mkdocstrings/mkdocstrings#383]
Hi there,

I have a project on GitLab that uses a json key for authentication. The key itself isn't in the repo for security reasons so when I run `mkdocs build` I get an exception that the file in question cannot be found. I'm a bit confused as to why `mkdocs` needs to check that the file exists - is it possible to override this behaviour? I'd like to use GitLab Pages so building the docs locally before removing the json file and then pushing isn't an option.

Thanks in advance!

**Comment by pawamoy** [comment]
Wrong repo :smile: ! This should be opened on the MkDocs repository instead.

You'll probably need to add details about the structure of your project, and the actual MkDocs warning, as without those it's quite hard to understand what you're doing.
