### ISSUE TITLE
Enable trim_doctest_flags in mkdocstrings?

### ISSUE THREAD

**Issue by thatlittleboy** [mkdocstrings/mkdocstrings#386]
### Discussed in https://github.com/mkdocstrings/mkdocstrings/discussions/384

<div type='discussions-op-text'>

<sup>Originally posted by **thatlittleboy** February 17, 2022</sup>
Hi, I'm not sure if this is under the purview of mkdocstrings, but I would like to check if it is possible to get the effect of `trim_doctest_flags` from the [sphinx-doctest ext](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-trim_doctest_flags) using mkdocstrings?

Essentially, with python code like this (excuse the function definition not making sense):
```python
def echo(arg1: str = None):
    """Header docstring.

    Example:

        >>> datetime.date.now()   # doctest: +SKIP
        datetime.date(2008, 1, 1)
        >>> foo('x')
        x

    :param arg1: A string.
    :returns: The original string.
    """
    return arg1
```

Is it possible to achieve such that the `# doctest: SKIP` is removed from the final HTML output? Thanks.</div>

----

I would like to propose to add similar functionality to mkdocstrings: removing `# doctest: xxx` and `<BLANKLINE>` flags from python codeblocks.

For reference, here is Sphinx' implementation:
- https://github.com/sphinx-doc/sphinx/blob/v4.4.0/sphinx/transforms/post_transforms/code.py#L104

From what I can see, there are a couple of things we need to ensure:
- apply the post-transformation only for python language blocks
- remove the flags via regex when parsing the codeblock source in the docstring
- avail this option to the end user via `mkdocs.yml`, default behaviour should be to remove these flags (as per Sphinx)
- add relevant tests to check this behaviour.

Where should the relevant changes be made in mkdocstrings?

**Comment by pawamoy** [comment]
Nice write-up :slightly_smiling_face: 

The changes should be made here:
https://github.com/mkdocstrings/griffe/blob/81f0333b1691955f6020095051b2cf869f0c2c24/src/griffe/docstrings/google.py#L434
(google parser)

You can indeed probably use a regex to remove doctest comments!
If you feel like it, you can do the same change for the Numpy parser in the same PR (do you want to send a PR?).

You can make it an option, defaulting to `True`, in the `parse` function of the same module(s).

**Comment by pawamoy** [comment]
Oh, doing the change in Griffe would make it available through the new Python handler only, not the legacy one. If you want it to be available in the legacy handler instead, the change needs to happen in pytkdocs:
https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/parsers/docstrings/google.py#L504

If you target the legacy handler, I'd highly appreciate if you could also implement it for the new handler :slightly_smiling_face:

**Comment by thatlittleboy** [comment]
Understood, thanks for pointing me in the right direction! I'll certainly give it a shot this weekend or the next. Will update here if I have any progress.

I'll take a look at both Griffe and the legacy handler; I think as long as the legacy handler is being supported, we should try to align both as far as possible.

**Comment by pawamoy** [comment]
This is now implemented in both the legacy and experimental handlers. Closing.
