### ISSUE TITLE
Render code cross-references as code

### ISSUE THREAD

**Issue by WillDaSilva** [mkdocstrings/mkdocstrings#396]
Currently the following is supported as per https://mkdocstrings.github.io/usage/#cross-references:

```markdown
With a custom title:
[`Object 1`][full.path.object1]

With the identifier as title:
[full.path.object2][]
```

It would be nice if the following variant was also supported:
```markdown
[`full.path.object2`][]
```

This would be just like `[full.path.object2][]`, except the link would be rendered as code. Alternatively/additionally, a rendering option to render all such links (of the form `[full.path.object2][]`) as code would be great.

**Comment by WillDaSilva** [comment]
Looks like ```[`full.path.object2`][]``` works. Not sure why I thought it didn't. Thanks!

**Comment by pawamoy** [comment]
Sorry I couldn't reply earlier! Thank you for coming back and closing the issue :+1: !
