### ISSUE TITLE
Are there relative autodocs identifiers?

### ISSUE THREAD

**Issue by lennizle** [mkdocstrings/mkdocstrings#406]
In a multirepo setup,  I need to reach `.py` files (through autodoc identifier) that after being pulled to the docs repo find themselves in a different folder structure.
 
```
docs_repo                          
├── components
│   └── engine_repo                  
│       ├── code.py
│       ├── docs
│       │   └── index.md
│       └── mkdocs.yml
├── docs
└── mkdocs.yml
```

In `index.md` is following autodoc identifier:
```
::: code.someClass
```

Now I am pulling this as git submodule and want to create a more extensive documentation. Mkdocstrings are now (only) active in docs_repo.

To make the docs_repo work with mkdocstrings I would need this path:
```
::: components.engine_repo.code.someClass
```
mkdocs.yml

```
plugins:
  - autolinks
  - monorepo
  - mkdocstrings:
      default_handler: python
```

Is there a way to write 'relative' identifiers? Can the handler be configured in way that I do not need to rewrite those paths? Or how should I go about this?

- *mkdocstrings* version: 0.18.1

**Comment by pawamoy** [comment]
New versions of mkdocstrings and the Python handlers have just been released. The handlers now accept a `paths` global option that can be used to specify paths in which to find packages/modules. The option works independently of the current working directory (relative paths are relative to mkdocs config file). I think this solves your use-case, so I'm closing, but feel free to reopen if I'm wrong!
