### ISSUE TITLE
mkdocstrings uses forwards incompatible code from jinja2 without constraining the dependency's upper bound

### ISSUE THREAD

**Issue by cpcloud** [mkdocstrings/mkdocstrings#414]
**Describe the bug**

`mkdocstrings` imports `contextfunction` from `jinja2` which has been removed in `jinja2==3`.

Without an upper bound on the dependency, projects can easily install a broken dependency graph.

Here's an example CI run in my project that fails: https://github.com/ibis-project/ibis/runs/5849500021?check_suite_focus=true

**To Reproduce**

Install jinja2==3 and mkdocstrings into an environment and try to build some documentation.

**Expected behavior**

Successfully built docs :)

**Information (please complete the following information):**
- OS: Linux
- Browser: N/A (unrelated to the problem)
- `mkdocstrings` version: 0.17.0

**Comment by pawamoy** [comment]
Hello, that's already fixed in version 0.18: https://github.com/mkdocstrings/mkdocstrings/commit/b37722716b1e0ed6393ec71308dfb0f85e142f3b
