### ISSUE TITLE
Feature: an equivalent to sphinx-autodoc-typehints

### ISSUE THREAD

**Issue by lucasiscovici-Loreal** [mkdocstrings/mkdocstrings#415]
**Is your feature request related to a problem? Please describe.**
Write once the typing (type hint) ant not twice (type hint, in docstring)

**Describe the solution you'd like**
This extension allows you to use Python 3 annotations for documenting acceptable argument types and return value types of functions. This allows you to use type hints in a very natural fashion. The extension [https://github.com/tox-dev/sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints)

<img width="944" alt="image" src="https://user-images.githubusercontent.com/96241836/162430507-937d779f-35d2-4ef1-af1f-0639980b30a5.png">

**Comment by pawamoy** [comment]
It should already be supported, see https://mkdocstrings.github.io/griffe/docstrings/#getting-annotationsdefaults-from-parent (new Python handlers, at least supported for parameters sections). Or are you using the legacy handler? I believe it's supported as well but I might be wrong.

**Comment by johnthagen** [comment]
Related to #389

**Comment by pawamoy** [comment]
So yeah, that should already work, even with the legacy handler:
https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/parsers/docstrings/restructured_text.py#L225-L231

Can you confirm which handler you're using @lucasiscovici-Loreal?

**Comment by pawamoy** [comment]
Closing, feel free to reopen a feature request in Griffe's bugtracker, asking for better Sphinx-style docstrings support.
