### ISSUE TITLE
Broken MkDocs code annotation

### ISSUE THREAD

**Issue by johnthagen** [mkdocstrings/mkdocstrings#417]
Navigate to:

https://mkdocstrings.github.io/recipes/#bind-pages-to-sections-themselves

Note the unrendered `#2` and `#3` (probably a copy-paste oversight):

<img width="595" alt="Screenshot 2022-04-09 193523" src="https://user-images.githubusercontent.com/10340167/162595017-5eb2a820-df3d-443e-a873-d173624d4e64.png">

**Comment by johnthagen** [comment]
Reported upstream:

- https://github.com/mkdocstrings/mkdocstrings/issues/418

**Comment by pawamoy** [comment]
Nice catch, thanks :slightly_smiling_face:
