### ISSUE TITLE
Automatic code reference pages recipe breaks on Windows

### ISSUE THREAD

**Issue by johnthagen** [mkdocstrings/mkdocstrings#418]
**Describe the bug**

The recipe: https://mkdocstrings.github.io/recipes/#bind-pages-to-sections-themselves

Works on *Nix systems, but seems to break on Windows.

**To Reproduce**

1. Checkout: https://github.com/johnthagen/python-blueprint (pre https://github.com/johnthagen/python-blueprint/commit/f8a396d878be9e971ef4bad1fc963db8654a5775)
2. Install `tox`
3. Run `tox -e docs`

```
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: python-blueprint\site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - reference\fact\__init__.md                                                                   
WARNING  -  A relative path to 'reference/fact☻95♥_init__.md' is included in the 'nav' configuration, which is not
            found in the documentation files                                                                      
WARNING  -  Documentation file 'reference\SUMMARY.md' contains a link to 'reference\fact☻95♥_init__.md' which is not
            found in the documentation files.   
```

**Expected behavior**

MkDocs project builds as expected, even on Windows.

**Information (please complete the following information):**
- OS: Windows 10
- `mkdocstrings` version: 0.18.0

```
mkdocs                     1.2.3
mkdocs-autorefs            0.3.1
mkdocs-gen-files           0.3.4
mkdocs-htmlproofer-plugin  0.8.0
mkdocs-literate-nav        0.4.1
mkdocs-material            8.2.1
mkdocs-material-extensions 1.0.3
mkdocstrings               0.18.0
mkdocstrings-python        0.6.3
mkdocstrings-python-legacy 0.2.2
```

**Comment by johnthagen** [comment]
Reported upstream:

- https://github.com/mkdocstrings/mkdocstrings/issues/418

**Comment by johnthagen** [comment]
I suspect this is due to Windows-specific path separators being injected into the generated `.md` file:

```md
* [fact](fact\__init__.md)
    * [cli](fact\cli.md)
    * [lib](fact\lib.md)
```

**Comment by johnthagen** [comment]
This is likely due to stdlib `Path` transparently changing based on the host OS.

Will probably need to use `PurePosixPath` somewhere when the paths are written into the Markdown file.

**Comment by pawamoy** [comment]
I'm pretty sure we're using `Path` at work, on Windows machines, and it works. Could it be related to this: https://github.com/oprypin/mkdocs-gen-files/issues/3? What version of mkdocs-gen-files do you have?

**Comment by pawamoy** [comment]
Actually it seems to be an encoding problem: `☻95♥` appears instead of `\`. @oprypin, sorry to bother, any idea?

**Comment by oprypin** [comment]
I don't know at the moment what these special symbols are about, but https://github.com/mkdocstrings/mkdocstrings/pull/419 is definitely heading in the right direction. It is invalid to put backslashes into nav.

**Comment by pawamoy** [comment]
I see, thanks @oprypin! I thought it would be supported.

**Comment by pawamoy** [comment]
Thanks for the fix @johnthagen!
