### ISSUE TITLE
"Parameter does not appear" warning problems

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocstrings/mkdocstrings#423]
The new warnings introduced by https://github.com/mkdocstrings/griffe/pull/63 (which solves #408) are causing me problems.

1. The word "parent" is extremely confusing - I assumed it referred to the argument names for a method of the same name in a parent class.
2. I think it breaks if the method is overloaded and has `@overload` methods without that argument name.

See https://github.com/samuelcolvin/dirty-equals/pull/32, and [this](https://github.com/samuelcolvin/dirty-equals/runs/6062213139?check_suite_focus=true) build in particular - the method with the docstring definitely has an argument named `expected_kwargs`.

The code causing the warning is [here](https://github.com/samuelcolvin/dirty-equals/blob/6e3ba9accef221340a12edc85a3ebea794baf954/dirty_equals/_other.py#L58-L76)

Any chance overloads could be considered, or if not - whether the warning could be optional?

---

 In this particular case, I'll revert griffe to get a new release out.

**Comment by pawamoy** [comment]
Ah, I think you simply need to document this parameter using the double stars:

```python
    def __init__(self, expected_value: JsonType = AnyJson, **expected_kwargs: Any):
        """
        Args:
            expected_value: Value to compare the JSON to, if omitted, any JSON is accepted.
            **expected_kwargs (Any): Keyword arguments forming a dict to compare the JSON to,
                `expected_value` and `expected_kwargs` may not be combined.
```

**Comment by samuelcolvin** [comment]
🙈 that solved it thank you and sorry for the noise.

Tweak to the warning wording would still be a good I think, but I'll close this issue as it's fixed for me.

**Comment by pawamoy** [comment]
No problem!

Do you have any suggestions? English is not my native language so my choice of words is always the best :slightly_smiling_face:

**Comment by pawamoy** [comment]
I'll change "parent" to "function" since it only works for functions anyway. And add a hint.

```python
                if name not in docstring.parent.parameters:  # type: ignore[union-attr]
                    message = f"Parameter '{name}' does not appear in the function signature"
                    for starred_name in (f"*{name}", f"**{name}"):
                        if starred_name in docstring.parent.parameters:  # type: ignore[union-attr]
                            message += f". Did you mean '{starred_name}'?"
                            break
                    _warn(docstring, line_number, message)
```

**Comment by samuelcolvin** [comment]
"Function" is perfect, thanks as ever for looking into this.
