### ISSUE TITLE
Better default styling for material parameter lists

### ISSUE THREAD

**Issue by analog-cbarber** [mkdocstrings/mkdocstrings#424]
Currently the styling of the tables used for parameter lists in the material style allows long type names
to squash the description column, making it harder to read:

<img width="747" alt="Screen Shot 2022-04-20 at 9 37 03 AM" src="https://user-images.githubusercontent.com/7408243/164243316-8e47f121-3ab6-4370-a526-9a0d154dbe1a.png">

I think this can be fixed with the appropriate CSS magic, but it would be nice if this project provided
a better default style rule to give the description column more space.

--
I am currently using mkdocs 1.30, mkdocs-material 8.2.9, mkdocstrings 0.18.1, mkdocstrings-python-legacy 0.2.2
from conda-forge.

**Comment by analog-cbarber** [comment]
The new handler looks much better! Simply having the different layout options is a huge improvement. Good job!

**Comment by pawamoy** [comment]
Closing, feel free to comment further!
