### ISSUE TITLE
Alternative Parameter Description Style

### ISSUE THREAD

**Issue by BlueGlassBlock** [mkdocstrings/mkdocstrings#426]
**Is your feature request related to a problem? Please describe.**
I wonder whether this project could support the parameter description style of sphinx-autodoc instead of a large table.

**Describe the solution you'd like**
Currently, mkdocstrings produces the signature in a table:

<table>
<tr>
	<td> Name
	<td> Type
	<td> Description
	<td> Default
<tr>
	<td> foo
	<td> Optional[FooType]
	<td> Foo description!
	<td> None
</table>

I want to have this sphinx style. (the default part can be thrown away)

- foo ([Optional](docs.python.org/3/library.typing.html#typing.Optional)[[FooType](http://some_made_up_domain.com)], *optional* = None): Foo description!

**Describe alternatives you've considered**
I can write my own templates, but I think adding official support could be very nice!

**Comment by pawamoy** [comment]
Already possible with the new handler: `docstring_section_style: list`. Closing, feel free to comment further!

**Comment by BlueGlassBlock** [comment]
> Already possible with the new handler: `docstring_section_style: list`. Closing, feel free to comment further!

It works quite fine for me! 👍 Except that the `optional` flag doesn't seem to show up 🤔 

Anyway I'm thanks for your great effort!
