### ISSUE TITLE
mkdocstrings: Template 'module.html' not found for 'python' handler and theme 'material'

### ISSUE THREAD

**Issue by zillionare** [mkdocstrings/mkdocstrings#427]
**Describe the bug**
ERROR    -  mkdocstrings: Template 'module.html' not found for 'python' handler and theme 'material'.
ERROR    -  Error reading page 'api.md': module.html
Traceback (most recent call last):
  File "/root/miniconda3/envs/bt/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocstrings/extension.py", line 120, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocstrings/extension.py", line 196, in _process_block
    rendered = handler.renderer.render(data, rendering)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/mkdocstrings/handlers/python/renderer.py", line 70, in render
    template = self.env.get_template(f"{data['category']}.html")
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/root/miniconda3/envs/bt/lib/python3.8/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: module.html

**To Reproduce**
pull source from https://github.com/zillionare/backtesting.git, then:

pip install poetry
poetry install -E doc -E dev -E test
mkdocs build

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
mkdocs  = { version = "^1.2.3", optional = true}
mkdocs-include-markdown-plugin  = { version = "^3.2.3", optional = true}
mkdocs-material  = { version = "^8.1.11", optional = true}
mkdocstrings  = { version = "^0.18.0", optional = true}
mkdocs-material-extensions  = { version = "^1.0.3", optional = true}
twine  = { version = "^3.8.0", optional = true}
mkdocs-autorefs = {version = "^0.3.1", optional = true}

**Additional context**

**Comment by pawamoy** [comment]
Hi, I get dependency resolution problems when trying to install your project and its dependencies:

```console
% poetry install -E doc -E dev -E test
Creating virtualenv zillionare-backtest-z6_oXPmY-py3.9 in /home/pawamoy/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  The current project's Python requirement (3.9.9) is not compatible with some of the required packages Python requirement:
    - zillionare-omicron requires Python >=3.8,<3.9, so it will not be satisfied for Python 3.9.9
  
  Because no versions of zillionare-omicron match >2.0.0a27,<3.0.0
   and zillionare-omicron (2.0.0a27) requires Python >=3.8,<3.9, zillionare-omicron is forbidden.
  So, because zillionare-backtest depends on zillionare-omicron (^2.0.0a27), version solving failed.

  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For zillionare-omicron, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by pawamoy** [comment]
Can you confirm you are running mkdocs from within the Poetry env, and not from an external env? In your description you wrote `mkdocs build` where it should probably be `poetry run mkdocs build` or `poetry shell` then `mkdocs build`.

**Comment by zillionare** [comment]
Thanks for take care of this case.

I'm using conda  env which is built with:

conda create -n bt python=3.8
conda activate bt
pip install poetry
poetry install -E doc -E dev -E test
mkdocs build

and if I run poetry shell, then mkdocs build:

(bt) root@ubuntu:/apps/backtest# poetry shell
Virtual environment already activated: /root/miniconda3/envs/bt
(bt) root@ubuntu:/apps/backtest# mkdocs build

give me same result.

I keep master branch untouched, it's still reproducible. You may reproduce this by yourself, or please tell my how can I help collect information for troubleshooting.

**Comment by PhML** [comment]
@zillionare I had a similar problem that was solved by removing `poetry.lock` file and reinstall. Looked like something went bad when I updated my dependencies.

Just in case I have those dependencies versions different from yours: 
```toml
twine  = { version = "^3.3.0", optional = true}
mkdocs-autorefs = {version = "^0.4.1", optional = true}
```

**Comment by zillionare** [comment]
> I have an issue when building your docs:
> 
> ```python
> ...
> File "/media/data/dev/backtesting/backtest/cli.py", line 21, in <module>
>     cfg = cfg4py.init(get_config_dir())
> ...
> File "/home/pawamoy/.cache/pypoetry/virtualenvs/zillionare-backtest-z6_oXPmY-py3.8/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
>     raise OSError(err, os.strerror(err))
> FileNotFoundError: [Errno 2] No such file or directory
> ```
> 
> If you have a hint on what's wrong (seems like a missing file/folder), I can fix it on my side to continue debugging. Otherwise I won't be able to help 😕

please set environment variable:

export __cfg4py_server_role__=DEV

than re-run mkdocs.

this variable will tell backtest to find config at source dir/backtest/config, otherwise, it'll go to ~/zillionare/backtest/config, which would never exist on you machine.

By the way, thanks for investigating.

Today I was able to run mkdocs build by tox -e lint, but still no lick at my conda development env.

this is my tox.ini:
`
[tox]
isolated_build = true
envlist = py38, lint

[testenv:lint]
whitelist_externals =
    poetry
    isort
    black
    flake8
    poetry
    mkdocs
    twine
commands =
    poetry install -E dev -E doc
    isort backtest
    black backtest
    flake8 backtest
    poetry build
    mkdocs build
    twine check dist/*
`

**Comment by zillionare** [comment]
> @zillionare I had a similar problem that was solved by removing `poetry.lock` file and reinstall. Looked like something went bad when I updated my dependencies.
> 
> Just in case I have those dependencies versions different from yours:
> 
> ```toml
> twine  = { version = "^3.3.0", optional = true}
> mkdocs-autorefs = {version = "^0.4.1", optional = true}
> ```

@PhML I have no luck after replace these two deps.

**Comment by pawamoy** [comment]
```console
% export __cfg4py_server_role__=DEV
% poetry run mkdocs serve          
INFO     -  Building documentation...
INFO     -  Cleaning site directory
/home/pawamoy/.cache/pypoetry/virtualenvs/zillionare-backtest-z6_oXPmY-py3.8/lib/python3.8/site-packages/mkdocstrings/handlers/python/__init__.py:13: UserWarning: The 'python-legacy' extra of mkdocstrings will become mandatory in the next release. We have no way to detect if you already specify it, so if you do, please ignore this warning. You can globally disable it with the PYTHONWARNINGS environment variable: PYTHONWARNINGS=ignore::UserWarning:mkdocstrings.handlers.python
  warnings.warn(
/home/pawamoy/.cache/pypoetry/virtualenvs/zillionare-backtest-z6_oXPmY-py3.8/lib/python3.8/site-packages/pandas_datareader/compat/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  PANDAS_VERSION = LooseVersion(pd.__version__)
INFO     -  Documentation built in 2.19 seconds
INFO     -  [14:57:39] Watching paths for changes: 'docs', 'mkdocs.yml', 'backtest'
INFO     -  [14:57:39] Serving on http://127.0.0.1:8000/
```

No errors!

**Comment by zillionare** [comment]
don't know why, yesterday I found tox -e lint pass, and today after I rebuild my conda env,  both mkdocs build and poetry run mkdocs build pass.

**Comment by pawamoy** [comment]
Thanks for coming back and closing!
