### ISSUE TITLE
Rendering docstring for undocumented functions/method

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [mkdocstrings/mkdocstrings#433]
Hi!

Thanks for the amazing package.

What if I have an undocumented class, e.g.

```python
class BoringClass:
    def __init__():
        pass

    def boring(self):
        pass
```

But I would like to generate the doc for the class with the method?

**Comment by pawamoy** [comment]
Hi! Thanks! You can set the `show_if_no_docstring` rendering option to true :)

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot :)
