### ISSUE TITLE
Warn for inaccessible sphinx inventory file instead of failing

### ISSUE THREAD

**Issue by analog-cbarber** [mkdocstrings/mkdocstrings#440]
Sometimes I need to build documentation when I do not have access to the internet (e.g.
riding the train to/from work). When this happens, I have to comment out any imports to get
it to work.

It would be nice if instead of failing mkdocstrings would just issue a warning and go on its
way just as if the import was never specified.

**Comment by pawamoy** [comment]
This is implemented. Errors will be logged instead of aborting the build.
