### ISSUE TITLE
Support "See also" section

### ISSUE THREAD

**Issue by andreas-vester** [mkdocstrings/mkdocstrings#452]
**Is your feature request related to a problem? Please describe.**
I am using the numpy docstring style. In some functions within a module, I have a "See also" section that links to other functions in the same module. It seems as if ``mkdocstrings`` isn't supporting this section, yet.

```
def add(a: int, b: int) -> int:
    """
    Adds two integer values.

    Parameters
    ----------
    a
        First integer value.
    b
        Second integer value.

    Returns
    -------
    int
        Result of a + b

    See Also
    --------
    sub : Subtract two integers.

    """
    return a + b
```

```
def sub(a: int, b: int) -> int:
    """
    Subtract two integer values.

    Parameters
    ----------
    a
        First integer value.
    b
        Second integer value.

    Returns
    -------
    int
        Result of a - b

    See Also
    --------
    add: Add two integers.

    """
    return a - b
```

**Describe the solution you'd like.**
It would be fantastic to see ``mkdocstrings`` supporting the "See also" section. I expect a link being generated in the rendered online documentation, which links to the referenced function.

**Comment by pawamoy** [comment]
Hello, thanks for the feature request.

I indeed didn't add support for the "See also" section of Numpydoc because to me it feels redundant. You can simply use regular markup and auto-references:

```python
def sub(a: int, b: int) -> int:
    """
    Subtract two integer values.

    Parameters
    ----------
    a
        First integer value.
    b
        Second integer value.

    Returns
    -------
    int
        Result of a - b

    See also:

    - [`add`][path.to.add]: Add two integers.
    """
    return a - b
```

But if you can show me some good uses of this section (in existing, online docs), I might reconsider :slightly_smiling_face: 
The difficulty here is to keep a common ground for all parsers without diverging too much (or at all).

**Comment by remivanbel** [comment]
Just wanted to mention that I also arrived here after a google search on why my 'See Also' was not recognized. 

I do understand the urge to keep it as clean as possible, and my opinion is not especially strong on the topic whether it is useful or not to have a 'See Also'. However, I do feel that it is a bit a weird failure mode that you don't expect when you are used to writing numpy type docstrings.

Big kudo's for the repository btw, I find it very simple and clean to work with!

**Comment by andreas-vester** [comment]
@pawamoy I'm somewhat sceptical with respect to add Markdown into a regular Python docstring. Usually, the "See also" section contains strings that are valid API names (https://developer.lsst.io/python/numpydoc.html#py-docstring-see-also).
Also, the style of the ``See also`` heading seems to be different than, let's say, the style of the ``Paramaters`` section when building the docs.
That is, I would appreciate a native implementation of the "See also" section.

**Comment by pawamoy** [comment]
I agree that using plain Markdown instead of a proper section feels weird. I guess we should try to support the Numpy doc style as best as we can. I'll see how that can be integrated nicely within Griffe's parsers.

**Comment by andreas-vester** [comment]
> I'll see how that can be integrated nicely within Griffe's parsers.

Any news/updates on that front?

**Comment by pawamoy** [comment]
Not yet, no. I'm pretty busy these days and don't have a lot of time for open source. Implementation details can be discussed here or in a draft PR on Griffe.

**Comment by pawamoy** [comment]
This should be supported now. Both Google and Numpy parsers support generic admonitions, including "See also". Such admonitions will generally fallback to the "note" style when rendered. Specific themes allow users to define their own admonition custom styles, see https://github.com/mkdocstrings/mkdocstrings/issues/664#issuecomment-2074569629.
