### ISSUE TITLE
Unsupported *Content tab* in a mkdocstrings parsed signature

### ISSUE THREAD

**Issue by Enn83** [mkdocstrings/mkdocstrings#457]
**Describe the bug**
When using a *[Content tab](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/)* in a signature/comment parsed by `mkdocstrings`, all the javascript on the current page don't work, resulting in an unworking search box and unusable scroll bar for TOC and site navigation. If I go to another page all javascript work well again. Also note that the *Content tab* is well displayed in the generated documentation.

**Error raised**
In the [F12] menu of Edge, I got the following message when I'm on a page that contain a *Content tab* in the generated documentation: 
`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'label[for=package.module.function--__tabbed_1_1]' is not a valid selector.`
(*Note that I replace the identifier by `package.module.function` for privacy reasons.*)

**To Reproduce**
It is reproducible even with a single file, with a single function, that must contain a `=== "Tab1"` in his signature.

**Expected behavior**
When a signature contain a *Content tab*, it should be visible - as it already does - but without broking the javascript on the current page.

**Information**
- OS: Windows 10
- Browser: Edge (Chromium)
- `mkdocstrings` version: 0.19.0

**Example of a breaking signature**
```python
def aFunction():
  '''
  Some comments...

  Example: Example of use
      === "Python code"
          ~~~python title="Example code"
          # Some python code
          ~~~
  
      === "Explaination"
          Some explainations ...
  '''
```

**Comment by pawamoy** [comment]
Could you try again with latest Material for MkDocs? It seems they fixed it on their side: https://github.com/squidfunk/mkdocs-material/commit/209856e724e67aac689744223f48f13e1c2fe3c4 (https://github.com/squidfunk/mkdocs-material/releases/tag/8.3.9)

**Comment by Enn83** [comment]
It seems partially fixed, all java script work well (the search box, TOC scroll, etc.), but there is an indentation problem, I think.

I updated all packages in my virtual env, here is the **`pip freeze`**: 
```
click==8.1.3
colorama==0.4.5
ghp-import==2.1.0
griffe==0.22.0
importlib-metadata==4.12.0
Jinja2==3.1.2
Markdown==3.3.7
MarkupSafe==2.1.1
mergedeep==1.3.4
mkdocs==1.3.1
mkdocs-autorefs==0.4.1
mkdocs-gen-files==0.3.5
mkdocs-literate-nav==0.4.1
mkdocs-material==8.4.1
mkdocs-material-extensions==1.0.3
mkdocs-section-index==0.3.4
mkdocstrings==0.19.0
mkdocstrings-python==0.7.1
packaging==21.3
Pygments==2.13.0
pymdown-extensions==9.5
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
pyyaml_env_tag==0.1
six==1.16.0
watchdog==2.1.9
zipp==3.8.1
```

This is the code I wrote in the file :

```python
def useless_method(self):
    '''
    Some comments...

    === "Python code"
        ~~~python title="Example code"
        # Some python code
        ~~~

    === "Explaination"
        Some explainations ...
    '''

    return (True, True, self.__useless)
```

... and this is the rendering : 
![image](https://user-images.githubusercontent.com/46783975/185945627-81b5785b-31ec-4c31-b0c0-4a6718d4b79e.png)

It seems all content in a Tab is converted as a code block, and if I unindent it (_dedent, outdent, I didn't find any standard definition for the opposite of indentation_) the Content tab is separated in two.

**Comment by Enn83** [comment]
It seems that the bug is fixed, as I have updated a lot of mkdocs related packages :
```
click==8.1.3
colorama==0.4.5
ghp-import==2.1.0
griffe==0.22.2
importlib-metadata==5.0.0        
Jinja2==3.1.2
Markdown==3.3.7
MarkupSafe==2.1.1
mergedeep==1.3.4
mkdocs==1.4.0
mkdocs-autorefs==0.4.1
mkdocs-gen-files==0.4.0
mkdocs-literate-nav==0.5.0       
mkdocs-material==8.5.6
mkdocs-material-extensions==1.0.3
mkdocstrings==0.19.0
mkdocstrings-python==0.7.1       
packaging==21.3
Pygments==2.13.0
pymdown-extensions==9.6
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
pyyaml_env_tag==0.1
six==1.16.0
watchdog==2.1.9
zipp==3.8.1
```

So I will close this issue !

**Comment by pawamoy** [comment]
Thanks for coming back and closing the issue!
