### ISSUE TITLE
 mkdocstrings might not work with editable installs in the new setuptools

### ISSUE THREAD

**Issue by AllenDowney** [mkdocstrings/mkdocstrings#463]
This is a preliminary bug report based on what I know so far, so I apologize if it is not complete.
`setuptools` just released version 64.0.0

https://setuptools.pypa.io/en/latest/userguide/development_mode.html

It features a new way of handling editable installations

https://peps.python.org/pep-0660/

It seems that the new mechanism doesn't work with mkdocstrings. If I do an editable install, mkdocstrings reports

```
ERROR    -  mkdocstrings: PACKAGENAME.MODULENAME could not be found
ERROR    -  Error reading page 'MODULENAME.md':
ERROR    -  Could not collect 'PACKAGENAME.MODULENAME'
```

If I install the same package normally (not editable), mkdocstrings works again.

We can work around the problem, but I wanted to post the issue now as it might affect others.

**Comment by pawamoy** [comment]
Hello, thanks for the heads up :slightly_smiling_face: 

From what I read in the docs:

> Under the hood, setuptools will try to create a special [.pth file](https://docs.python.org/3/library/site.html#module-site) in the target directory (usually site-packages) that extends the PYTHONPATH or install a custom [import hook](https://docs.python.org/3/reference/import.html).

...it should already be supported (since we support .pth files). However maybe their .pth file is not what Griffe expects. Could you post the contents of such a file? It's probably named `PACKAGENAME.pth`.

**Comment by AllenDowney** [comment]
Hmm. Looking around, I don't see `zamba.pth` anywhere. One complication might be that I am pip installing into a Conda environment.

Maybe let's see if others run into the problem and maybe we can get a less complicated example to work from. In the meantime, the workaround for me is to hold back `setuptools` in `pyproject.toml`:

```
[build-system]
requires = [
    "setuptools<=63",
    "wheel",
]
build-backend = "setuptools.build_meta"
```

Note that holding back `setuptools` in `requirements.txt` does not work because those aren't the requirements installed during the build process.

**Comment by pjbull** [comment]
Here are all the records present in `site-packages` with the editable install:

[nbautoexport-0.5.0+3.g01818e8.dirty.dist-info.zip](https://github.com/mkdocstrings/mkdocstrings/files/9499191/nbautoexport-0.5.0%2B3.g01818e8.dirty.dist-info.zip)

**Comment by pawamoy** [comment]
Thanks @pjbull. However the docs say setuptools installs a .pth file or a custom hook (à la `editables` I guess, which we already support), and I'd need to see that instead of the dist info.

**Comment by pjbull** [comment]
Ah, yep. Sorry I missed that those just sit directly in `site-packages`. Here's the contents:

 - `__editable__.nbautoexport-0.5.0+3.g01818e8.dirty.pth`:

```python
import __editable___nbautoexport_0_5_0_3_g01818e8_dirty_finder; __editable___nbautoexport_0_5_0_3_g01818e8_dirty_finder.install()
```


 - `__editable___nbautoexport_0_5_0_3_g01818e8_dirty_finder.py`:

```python
import sys
from importlib.machinery import ModuleSpec
from importlib.machinery import all_suffixes as module_suffixes
from importlib.util import spec_from_file_location
from itertools import chain
from pathlib import Path

MAPPING = {'nbautoexport': '/Users/bull/code/nbautoexport/nbautoexport'}
NAMESPACES = {}
PATH_PLACEHOLDER = '__editable__.nbautoexport-0.5.0+3.g01818e8.dirty.finder' + ".__path_hook__"


class _EditableFinder:  # MetaPathFinder
    @classmethod
    def find_spec(cls, fullname, path=None, target=None):
        for pkg, pkg_path in reversed(list(MAPPING.items())):
            if fullname == pkg or fullname.startswith(f"{pkg}."):
                rest = fullname.replace(pkg, "", 1).strip(".").split(".")
                return cls._find_spec(fullname, Path(pkg_path, *rest))

        return None

    @classmethod
    def _find_spec(cls, fullname, candidate_path):
        init = candidate_path / "__init__.py"
        candidates = (candidate_path.with_suffix(x) for x in module_suffixes())
        for candidate in chain([init], candidates):
            if candidate.exists():
                return spec_from_file_location(fullname, candidate)


class _EditableNamespaceFinder:  # PathEntryFinder
    @classmethod
    def _path_hook(cls, path):
        if path == PATH_PLACEHOLDER:
            return cls
        raise ImportError

    @classmethod
    def _paths(cls, fullname):
        # Ensure __path__ is not empty for the spec to be considered a namespace.
        return NAMESPACES[fullname] or MAPPING.get(fullname) or [PATH_PLACEHOLDER]

    @classmethod
    def find_spec(cls, fullname, target=None):
        if fullname in NAMESPACES:
            spec = ModuleSpec(fullname, None, is_package=True)
            spec.submodule_search_locations = cls._paths(fullname)
            return spec
        return None

    @classmethod
    def find_module(cls, fullname):
        return None


def install():
    if not any(finder == _EditableFinder for finder in sys.meta_path):
        sys.meta_path.append(_EditableFinder)

    if not NAMESPACES:
        return

    if not any(hook == _EditableNamespaceFinder._path_hook for hook in sys.path_hooks):
        # PathEntryFinder is needed to create NamespaceSpec without private APIS
        sys.path_hooks.append(_EditableNamespaceFinder._path_hook)
    if PATH_PLACEHOLDER not in sys.path:
        sys.path.append(PATH_PLACEHOLDER)  # Used just to trigger the path hook

```

**Comment by pawamoy** [comment]
That's perfect, thanks. I see we could regex-find the `MAPPING` value, to start at least. We'll need to try editable installs for namespace packages as well (great to learn they support them), but that can be done later. By the way all this detection happens in Griffe, if someone wants to try and send a PR :) Otherwise I'll eventually get to it.

**Comment by sanand0** [comment]
Workaround: using [strict editable installs](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#strict-editable-installs) solves this. However, the implementation details are not finalized yet, and may change in the future.

Instead of:

```shell
pip install -e .
```

... we could use:

```shell
pip install -e . --config-settings editable_mode=strict
```

**Comment by pawamoy** [comment]
This should be supported in the next release of Griffe.

**Comment by stefsmeets** [comment]
Can anyone confirm that this is working for them? I still get the 'module could not be found' errors with my editable install on the latest version:

- mkdocs: 1.5.2
- griffe: 0.34.0
- mkdocstrings: 0.22.0

Only with the strict editable install solution from @sanand0 I can get it to work.

**Comment by pawamoy** [comment]
It's possible that setuptools has changed again how their editable installs work. If you can share a public repository reproducing the issue, I can investigate.

**Comment by stefsmeets** [comment]
Thanks, this is with setuptools: 68.0.0, Python 3.11

I'm currently working on https://github.com/GEMDAT-repos/GEMDAT where I'm running into this issue.

**Comment by pawamoy** [comment]
Hmmm seems to work fine? I installed the project with `pip install -e .[docs]`. I do have `__editable___GEMDAT_0_0_1_finder.py` and `__editable__.GEMDAT-0.0.1.pth` in my venv's site-packages. I can see the generated API docs.

**Comment by stefsmeets** [comment]
Ah I see it only happens in the docs branch: `git checkout docs --`

**Comment by pawamoy** [comment]
Debugging from the other way, yep, we have this in the editable module:

```python
MAPPING = {'gemdat': '/media/data/dev/GEMDAT/src'}
```

...while Griffe expects this:

```python
MAPPING = {'gemdat': '/media/data/dev/GEMDAT/src/gemdat'}
```

...because for it then [picks up the parent directory of this value](https://github.com/mkdocstrings/griffe/blob/b8236391f4ac8b16e9ee861c322e75ea10d6a39b/src/griffe/finder.py#L365) (`.parent`).

**Comment by pawamoy** [comment]
Oh right, I didn't notice modules were stored directly under `src` and not `src/gemdat` :sweat_smile: I would have immediately pointed at that otherwise :slightly_smiling_face:

**Comment by pawamoy** [comment]
You're welcome!

Also, it was working before because Griffe would not find `gemdat` and fallback on inspection, trying (and succeeding) to import it, and you were only injecting docs with `::: gemdat`. Within the docs branch, you're now also injecting docs for `gemdat.plots`, and it happens that `inspect.getmembers` returns submodules of the gemdat packages, **except the `plots` submodule**, probably because it's a folder and needs to be imported to appear in its parent.

**Comment by pawamoy** [comment]
Finally, note that you don't have to rely on Griffe's ability to understand editable modules: you can tell it to search directly in `src` (now that you have a proper layout) with this:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
```

**Comment by stefsmeets** [comment]
Excellent feedback, thanks! I will also add the `paths: [src]` specification.
