### ISSUE TITLE
Add additional `show` settings to markdown generator

### ISSUE THREAD

**Issue by Archmonger** [mkdocstrings/mkdocstrings#466]
**Is your feature request related to a problem? Please describe.**
There are certain circumstances where I only want to embed the args/returns, and no title/description/etc.

**Describe the solution you'd like**
The main concept here is the ability to enable/disable rendering for all major blocks.

Expand the current set of `show` settings (currently only `show_root_heading` and `show_source`) to also include the following:

- `show_title`
- `show_description`
- `show_parameters`
- `show_returns`
- `show_raises`

... and for classes:

- `show_method_title`
- `show_method_description`
- `show_bases`

A nice to have bonus feature would be the ability to globally change these default values.

**Describe alternatives you've considered**
Could alternatively develop a `use_template="path_to_template.html"` variable that allows the user to select their own Jinja template for that one specific include tag to use.

This would require additional documentation as to what context variables are accessible within the jinja context.

I wouldn't advise doing this though, as it seems unnecessarily complex for most people who just wanna hide basic stuff without changing the core rendering behavior.

**Additional context**
N/A

**Comment by thatlittleboy** [comment]
This is probably more relevant on the handler-level, e.g. [mkdocstrings-python](https://github.com/mkdocstrings/python) if you're talking about python, rather than mkdocstrings. Since that's the cog in the wheel that handles the rendering into html.

@pawamoy Would you accept a PR in `mkdocstrings-python` for this? I'm thinking of an approach like:

- make the python handler accept all these new "show" config options, default will be True for all.
- modify base templates for docstrings/ to only render if `kind == "Parameters" and show_parameters`

Should be simple enough to implement, the only thing is that we'll be introducing a ton of new config options.

**Comment by pawamoy** [comment]
Yes, I would accept such a PR :rocket: 
Indeed that's quite a lot of options. I'm not yet sure how I would like to handle the growing number of options in the future (nest them? keep them flat? factorize them somehow?), so I suggest we don't lose time waiting, and we'll see later if we need to reorganize them or not :slightly_smiling_face:

**Comment by Archmonger** [comment]
On the bright side they're basically invisible settings in user land.

Even if the amount of parameters increase in the future, it's probably pretty rare to see occasions where users will modify a substantial amount of them at once.

Being able to globally change the defaults would be nice though.

**Comment by thatlittleboy** [comment]
Cool cool, I'll get on it 🚀

**Comment by Archmonger** [comment]
Not a global override, but rather a global default settings change.

For example, perhaps 90% of the time I don't want `show_bases`, but there might be specific occasions where it's needed.

**Comment by thatlittleboy** [comment]
Yep, should be possible, if I understand u correctly. We'll expose the option globally (i.e,. you'll set `show_bases: false` in `mkdocs.yml`), then specify `show_bases: true` in the autodoc specification where you want to show base. For precise control.

**Comment by pawamoy** [comment]
> Even if the amount of parameters increase in the future, it's probably pretty rare to see occasions where users will modify a substantial amount of them at once.

What worries me a bit is more the maintenance (and deprecation periods that will ensue if we reorganize options), more than the list being long in users' configs. But as I said, I'll see that later :slightly_smiling_face:

**Comment by pawamoy** [comment]
Implemented in https://github.com/mkdocstrings/python/pull/56, thanks @thatlittleboy and @Archmonger!
