### ISSUE TITLE
How to make Admonition default as expanded

### ISSUE THREAD

**Issue by eul94458** [mkdocstrings/mkdocstrings#468]
Notes and author stuffs and infos in the docstring seem rendered as admonitions of Mkdocs.
But they are all default as collapsed and not convenient.
I was unable to figure out where is this rendering magic happening. 
If there is a way to configure it, I would love to hear.

**Comment by betolink** [comment]
I ran into the same issue, I was looking at this project setup and couldn't find where to add something like `"admonitions_open: true"`

**Comment by betolink** [comment]
workaround: if we follow the original convention from [mkdocs-material](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) we can render them expanded:

```python
class MyClass:

  def some_method(self):
  """
  ???+ Tip
      The Tip admonition will be open!
      if we want it closed we just omit the + 
      or use the original syntax from mkdocstrings (just `Tip:`)
  """

```

**Comment by thangckt** [comment]
I am also looking for this

**Comment by pawamoy** [comment]
Version [0.10.0](https://mkdocstrings.github.io/python/changelog/#0100-2023-05-07) of the Python handler now renders admonitions open by default
