### ISSUE TITLE
Support numpydoc style examples sections (>>>) as written in numpydoc guide

### ISSUE THREAD

**Issue by machow** [mkdocstrings/mkdocstrings#471]
**edit:** wait--I'm noticing that example sections with `>>>` are parsed to some degree. Let me dig a bit deeper into what might be happening....!

**Is your feature request related to a problem? Please describe.**

Currently, if a user wants to add examples in their numpydoc-style docstrings, they need to use a work-around provided in this [mkdocstrings recipe](https://numpydoc.readthedocs.io/en/latest/format.html#examples). This is a handy workaround, and does the job.

However, it also means that users need to tailor their docstrings specifically to mkdocstrings :/.

**Describe the solution you'd like**

Would it be possible to support numpydoc-style example sections, as shown and rendered in the [Examples section](https://numpydoc.readthedocs.io/en/latest/format.html#examples) of the numpydoc reference? (note the lack of indentation in the screenshot below).

<img width="962" alt="image" src="https://user-images.githubusercontent.com/2574498/186947637-5e3294a1-ec3f-4f42-aee4-8542f4615a2f.png">

**Describe alternatives you've considered**

Re-write example docstrings in the specific format that mkdocstrings can render.

**Additional context**

If support for this would be useful, and you can provide some pointers into where the implementation would need to happen, then I'm happy to look into it! (Ideally in the python-legacy version!)

**Comment by machow** [comment]
It looks like this is an issue with a recent release of `docstring_parser` being used by pytkdocs (or some combination of pytkdocs and the parser), since downgrading to `docstring_parser==1.3` resolved. I'll try to dig a bit further, and open issues on the relevant repos!

**Comment by pawamoy** [comment]
Thank you for coming back, updating and closing the issue, this is appreciated :+1:
