### ISSUE TITLE
mkdocstrings hangs on `Collecting data`. How to increase verbosity?

### ISSUE THREAD

**Issue by stolarczyk** [mkdocstrings/mkdocstrings#472]
First of all, thanks for developing this project, it seems to be really useful.

My question is whether there's a way to increase mkdocstrings verbosity in mkdocs output. When I build docs for my project mkdocstrings hangs like so:

```
mkdocs build -v
```

```
...
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: <dir>/site 
DEBUG    -  Reading markdown pages.
DEBUG    -  Reading: README.md
DEBUG    -  Reading: API_documentation_mkdocstrings.md
DEBUG    -  mkdocstrings: Matched '::: <pkg_name>.data_models.Status'
DEBUG    -  mkdocstrings: Using handler 'python'
DEBUG    -  mkdocstrings: Collecting data
```

I presume that's an issue on my end but I need some details on what mkdocstrings is actually stuck at.

*mkdocstrings* version: 0.19.0

**Comment by muonmax** [comment]
Bump

**Comment by adelapie** [comment]
I also have the same problem. It seems mkdocstrings cannot handle multi-file / multi-module projects?

**Comment by jordankbartos** [comment]
Me too. I have tried older versions of `mkdocs`, `mkdocstrings`, and `mkdocstrings-python`. So, I also suspect it's something incorrect in my configuration or project structure. But it sure is hard to debug without more visibility into what's going on.

```
 mkdocs v1.3.1
 mkdocstrings v0.19.0
 mkdocstrings-python v0.7.1
```

**Comment by pawamoy** [comment]
Hello all, thank you for reporting this issue. Do you a public repository that I could to replicate the issue? The new python handler has less chance to freeze compared to the legacy one, so this seems surprising to me.

**Comment by rudolfbyker** [comment]
@stolarczyk @muonmax @jordankbartos This sounds like a problem I had, which was caused by an infinite loop in Griffe's docstring parser. Which version(s) are you using? Please post output of `pip show griffe`. pip does not always update dependencies...

**Comment by adelapie** [comment]
I'm using the last version Version: 0.22.0

To reproduce just create a multi module project in python and try to import docstrings via e.g. ::: module1.test, it doesn't matter what comes after the point, it hangs

**Comment by pawamoy** [comment]
It's working fine in my projects with lots of modules :smile: I definitely need a reproducible example: pyproject.toml/requirements.txt, mkdocs config and files, and some code.

What OS are you all using?

**Comment by MRosiek** [comment]
Hi,
I have also encountered same issue as few guys mentioned before. `Mkdocs build -v` command is hanging on `Collecting data`. I've managed to isolate project structure to reproduce the issue. I'm attaching project in zip file which contains `pyproject.toml` and `mkdocs.yaml`. I discovered that it happens when in `root directory` of the project `__init__.py` file is present. When you try to remove it, it works like a charm, but when its present it hangs.

PS. If it is more convenient for you I can create special repository to host that little project.

I'm using Windows 10.

Some information about my env and used packages(not all of them):

> Python version: 3.9.12
> griffe                        0.23.0    Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation 
> mkdocs                        1.4.2     Project documentation with Markdown.
> mkdocs-autorefs               0.4.1     Automatically link across pages in MkDocs.
> mkdocs-material               8.5.8     Documentation that simply works
> mkdocs-material-extensions    1.1       Extension pack for Python Markdown and MkDocs Material.
> mkdocstrings                  0.19.0    Automatic documentation from sources, for MkDocs.
> mkdocstrings-python           0.7.1     A Python handler for mkdocstrings.

[reproduction_project.zip](https://github.com/mkdocstrings/mkdocstrings/files/9953336/reproduction_project.zip)

**Comment by pawamoy** [comment]
Thanks you so much @MRosiek, this will help a lot!

**Comment by pawamoy** [comment]
OK, I was able to replicate and write a fix, I'll release it soon.
That said: having an `__init__.py` module at the root of the repository seems wrong. Do some of you have a use-case for it?
Also: since `src` is added to the search paths in `mkdocs.yml`, there's no need to identify your object by prefixing it with `src` in `::: src.package1`. Are the other commenters doing that as well? It is discouraged/wrong to specify `:::` paths with folders that are not namespace packages nor regular packages.

**Comment by MRosiek** [comment]
> OK, I was able to replicate and write a fix, I'll release it soon.

Im glad you managed to fix that based on my finding. Maybe this will sound stupid but it means a lot for me as it is my first contribution of some kind here on GitHub ;).

> That said: having an `__init__.py` module at the root of the repository seems wrong. Do some of you have a use-case for it?

I have some issues with structure of my current project which contains relative imports in modules (like e.g. `... folder_name(folder - not package).module_name import some_class`. When I remove the the root `__init__.py` file the build using mkdocs ends with error. But honestly i dont know what is going on unfortunately. I ve read somewhere that adding `__init__.py` file could potentially solve the issue of  `Attempted relative import in non-package`. I would need to investigate it further to give you more details.

**Comment by pawamoy** [comment]
> Im glad you managed to fix that based on my finding. Maybe this will sound stupid but it means a lot for me as it is my first contribution of some kind here on GitHub ;).

That doesn't sound stupid at all, on the contrary! The first interactions in open source communities are quite important, as they sometimes define how people will feel about open source for a long time, be it as authors or contributors. I'm very glad you chose to contribute here for your first time, and I hope you will enjoy continuing to contribute to this or other open source projects and communities :smiling_face_with_three_hearts: 

About packaging and Python modules: I personally avoid relative imports, and always use absolute ones:

```
repo/
    package/
        __init__.py
        module_a.py
        module_b.py
```

```python
# package/module_b.py
from package.module_a import thing
```

**Comment by lpurdy01** [comment]
I also ran into this issue, and @MRosiek removing the `__init__.py` from the base directory fixed it.
