### ISSUE TITLE
create documentation for an entire package

### ISSUE THREAD

**Issue by mahmoudyusof** [mkdocstrings/mkdocstrings#481]
right now there is a package containing multiple modules containing multiple classes, is there a way to generate automatically all the docs needed just by mentioning the top level package?

**Comment by pawamoy** [comment]
Hi, yes, you can either inject the documentation for the whole package, recursively, using `::: my_package` in your Markdown page, or you can [follow this recipe](https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages).
