### ISSUE TITLE
Is there a configuration for multiline function/method sigunatures?

### ISSUE THREAD

**Issue by griff-rees** [mkdocstrings/mkdocstrings#485]
Thanks for the excllent project. This is a layout/formatting question, and I can of course can turn this into a ticket/feature request. Apologies as well if this actually falls under a plugin..

- *mkdocstrings* version: `0.19.0` with `python` `extra`

In part mirroring [Black's mulit-line layout of function definitions](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines) is there some option for configuring function definition layouts to be on multiple lines, especially if that can then facilitate presenting [type hinted](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#functions) function annotation information as well? 

<img width="839" alt="Screenshot 2022-10-12 at 13 11 40" src="https://user-images.githubusercontent.com/60181741/195339479-068612a6-1078-43b9-9993-b8d941b5ce75.png">

**Comment by pawamoy** [comment]
Hi, yes, you'll need to set the `separate_signature` option to `true`, and make sure Black is installed and available.

**Comment by griff-rees** [comment]
Ah sweet and well done for including a [Black](https://black.readthedocs.io/en/stable/) warning! 
```pycon
WARNING  -  mkdocstrings_handlers: Formatting signatures requires Black to be installed.
```
Sorry for missing the [documentation](https://mkdocstrings.github.io/python/usage/#globallocal-options):

<img width="718" alt="Screenshot 2022-10-13 at 23 17 47" src="https://user-images.githubusercontent.com/60181741/195721146-59a3684d-cbd5-4da3-8ecb-e9ad7e2ea9cf.png">

Thanks again.

PS: I wonder if type hinting syntax highlighting could be more prominent but my `neovim` config is pretty bad on that so I'm not aware of any easy solution...

**Comment by pawamoy** [comment]
I'm not sure why you mention Neovim :confused: 
Syntax highlighting is provided by Pygments (and pymdown-extensions' highlight?), nothing we can do in mkdocstrings.

**Comment by griff-rees** [comment]
Apologies for the ambiguity and slow reply. I mention Neovim purely to acknowledge that syntax highlighting is a hard problem, especially of an evolving language, and I bet type hinting one of the harder shifts. Don't mean it as criticism (and I'm a huge fan of Neovim). Thank again.

**Comment by pawamoy** [comment]
Of course, no problem, I didn't take it as criticism. Thanks for the update ^^
