### ISSUE TITLE
Indention within bullet list

### ISSUE THREAD

**Issue by andreas-vester** [mkdocstrings/mkdocstrings#486]
**Add detailed information, like**
- *mkdocstrings* version: 0.19.0
- *mkdocstrings-python* version: 0.7.1

I have a bullet list within my docstring (numpy style). Within this list, I have some further explanations for individual bullet points. ``mkdocstrings`` doesn't seem to render the idention correctly.

Consider the following example:

```
def docstest(int_val: int, float_val: float) -> float:
    """Function to showcase docstring problems.

    This docstring demnonstrates some issues using ``mkdocstrings`` with respect to the
    indention of text within a bullet list.

    Parameters
    ----------
    int_val
        Integer value. Some integer values are:

        - integer value 1: 5
        - integer value 2: 6
        - integer value 3: 7

          Any value without a decimal separator can be interpreted as an integer value.

        - integer value 4: 8
    float_val
        Floating point point value

    Returns
    -------
    float:
        Sum of ``a`` and ``b``

    """
    pass
```

The output looks as follows:

![grafik](https://user-images.githubusercontent.com/29901736/196044463-996491b8-ac5b-495f-a621-ad18a1a7cf52.png)

The text should be aligned with the start of the text "integer value 3: 7". Also, the blank line before "Any value without a decimal..." is bothering me.

I am not sure whether this is a bug or if I am supposed to change the docstring itself?

**Comment by pawamoy** [comment]
Hi, this is not a bug, this is how Markdown works. Try using four spaces of indentation in front of "Any value..." instead of two. If the blank line before it bothers you, remove it and add two trailing spaces on the line above.

```
...

- integer value 3: 7  
    Any value without a decimal separator can be interpreted as an integer value. 
```

**Comment by andreas-vester** [comment]
@pawamoy You are right with respect to markdown.

However, the docstring is not necessarily markdown. Trailing spaces in Python code (even in docstrings) might be removed (e.g. by the [black formatter](https://black.readthedocs.io/en/stable/)).

Using four spaces as idention lead to exactly the same result as described in the first post.

When using [sphinx](https://www.sphinx-doc.org/en/master/) with the exact same code/docstring, it will render the idention correctly/as expected.

**Comment by pawamoy** [comment]
You're right, a docstring is not necessarily written as Markdown. But you're using mkdocstrings here, so it wouldn't make sense to use something else. That Black could potentially remove trailing spaces is an issue with Black, not mkdocstrings. Unless you're comparing it to Sphinx + Myst, the comparison doesn't hold either as Sphinx uses restructuredtext.

What I'm trying to say here really, is that it boils down to how Markdown is parsed by Python-Markdown, and mkdocstrings has no role to play in this.

I'll try to see later how one could achieve what you want in Markdown :)

**Comment by andreas-vester** [comment]
> I'll try to see later how one could achieve what you want in Markdown :)

Any new ideas how to solve that issue? Or is it simply not possible?

**Comment by pawamoy** [comment]
https://github.com/mkdocstrings/mkdocstrings/issues/487#issuecomment-1280387796
