### ISSUE TITLE
Allow using *relative imports* to cross-reference inside the project

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [mkdocstrings/mkdocstrings#489]
**Is your feature request related to a problem? Please describe.**

When writing cross-references inside the project, links become a bit too verbose. For example, if we have:

```py
# module some.deep.nested.module_a
class A:
    """A class.

    We reference [B][some.deep.nested.module_b.B].
    """

class AA:
    """AA class.

    We reference [A][some.deep.nested.module_a.A].
    """
```

```py
# module some.deep.nested.module_b
class B:
    """B class.

    We reference [A][some.deep.nested.module_a.A].
    """
```

Here references can get really difficult to write. Another alternative would be to write `[some.deep.nested.module_a.A][]`, which saves a few chars (depending on the name of the leaf symbol), but then the produced documentation becomes too verbose if we are already at the context of a `some.deep.nested` package.

**Describe the solution you'd like**

Allow writing local cross-references using *relative* imports and local symbols. In the example above:

```py
# module some.deep.nested.module_a
class A:
    """A class.

    We reference [B][.module_b.B].
    """

class AA:
    """AA class.

    We reference [A][].
    """
```

```py
# module some.deep.nested.module_b
class B:
    """B class.

    We reference [.module_a.A][].
    """
```

**Describe alternatives you've considered**

Just using the fully qualified symbol as stated above.

**Additional context**

None really, just that I know it would be hard to implement :)

**Comment by pawamoy** [comment]
Now implemented, closing :slightly_smiling_face: See https://mkdocstrings.github.io/python/usage/configuration/docstrings/#relative_crossrefs.
