### ISSUE TITLE
Feature: Type links in function signatures

### ISSUE THREAD

**Issue by tlambert03** [mkdocstrings/mkdocstrings#492]
*Apologies if I've missed this discussed elswhere*

I'm like to use `show_signature_annotations`.  And I'm wondering if it's possible to have the types be rendered with links to their references (as they would in the docstring parameters).

For example,

```python
def iter_axis(self, axis: str) -> Iterator[Union[Position, Channel, float]]:
    ...
```

is rendered as:

![Screen Shot 2022-11-21 at 11 10 04 AM](https://user-images.githubusercontent.com/1609449/203103332-ae3d4923-4535-4094-b6bc-171d7d4f4885.png)

```html
<code class="highlight language-python">
    <span class="n">iter_axis</span>
    <span class="p">(</span>
    <span class="n">axis</span>
    <span class="p">:</span>
    <span class="nb">str</span>
    <span class="p">)</span>
    <span class="o">-&gt;</span>
    <span class="n">Iterator</span>
    <span class="p">[</span>
    <span class="n">Union</span>
    <span class="p">[</span>
    <span class="n">Position</span>
    <span class="p">,</span>
    <span class="n">Channel</span>
    <span class="p">,</span>
    <span class="nb">float</span>
    <span class="p">]]</span>
</code>
```

... and I would love it if there was an option for `Position`, `Channel`, etc... to be anchor links to their respective references.

@pawamoy, If I haven't just missed it, and this is indeed not yet possible, I'd be willing to take a stab at an implementation if you want to give me a quick pointer to the files you would begin modifying.

**Comment by pawamoy** [comment]
This was implemented as an insiders feature, see https://mkdocstrings.github.io/python/usage/configuration/signatures/#signature_crossrefs
