### ISSUE TITLE
Handle Google style docstrings for Python properties

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [mkdocstrings/mkdocstrings#499]
Hey, thank you so much for your work on `mkdocstrings`!

Currently, `mkdocstrings` has support for methods that have docstrings that follow the Google style, but sadly it does not have support for properties (`@property`) that follow the Google style for Python docstrings.

So, currently, I have to do something like:

```py
class MyClass:
    # ...
    @property
    def my_int_property(self) -> int:
        """My brief description here.

        Returns:
            int: A typically redundant description here.
        """
```

Ideally, I would just do something like

```py
class MyClass:
    # ...
    @property
    def my_int_property(self) -> int:
        """int: My brief description here."""
```

In a perfect world, `mkdocstrings` would even pick up the name of the return value from the property name itself!

**Comment by pawamoy** [comment]
Hello! You can just remove `int:` from the docstring: the type is already fetched from the signature. Let me know if that works for you.

**Comment by rodrigogiraoserrao** [comment]
You are right, I should remove `int:` from the docstring because `mkdocstrings` reads it from there, but that still doesn't address my issue of handling docstrings for properties.

**Comment by pawamoy** [comment]
Google-style documented properties are definitely supported. Could you expand on what your issue actually is? Is the property not showing up in the generated docs? Is it showing up but without the docs trying? Something else?

**Comment by rodrigogiraoserrao** [comment]
I was looking back to this and I can't really see what I was thinking / trying to do. Properties are documented as expected and they get appropriate labels...

I'll close this issue; thanks for your time!

**Comment by pawamoy** [comment]
Thanks for coming back and closing!
