### ISSUE TITLE
Unexpected error when trying to include docstrings from compiled Cython module

### ISSUE THREAD

**Issue by jewaniuk** [mkdocstrings/mkdocstrings#514]
**Describe the bug**
I have tried to include the docstring from a function called `getDim` in the `quotonic.fock` module. To do this, I have include `::: quotonic.fock.getDim` in `docs/fock.md`. Unfortunately, when I try to create the documentation, I get the following error:

`ERROR - mkdocstrings: Template 'alias.html' not found for 'python' handler and theme 'material'`
`ERROR - Error reading page 'fock.md': alias.html`

Please see for linked repository below for further details on the file tree, and follow the instructions below to reproduce the error. My project was generated using [cookiecutter-poetry](https://fpgmaas.github.io/cookiecutter-poetry/). I typically run `poetry build` to generate the Cython extensions, followed by `make install` to set up the project using poetry. Then, I run `make docs` to create the documentation and serve it locally, however, this is where the error arises. I am unsure if poetry is required to reproduce this error. I sincerely apologize if it is! I can try to find a way to reproduce it without poetry if necessary.

**To Reproduce**
**If `poetry` is required to reproduce this error, I know that this reproduces it: **
1. Clone the [quotonic-public](https://github.com/jewaniuk/quotonic-public) repository.
2. Run `poetry build`
3. Run `make install`
4. Run `make docs`

**If `poetry` is not required to reproduce this error, I assume this would reproduce it: **
1. Clone the [quotonic-public](https://github.com/jewaniuk/quotonic-public) repository.
2. `python setup.py install`
3. `mkdocs serve`

**Expected behavior**
I expected to see documentation for the `getDim` function just as it shows up for `quotonic.clements.Mesh`, a pure python file.

**Screenshots**
This is the output I get when the error occurs.
![Screenshot 2023-01-18 at 3 42 44 PM](https://user-images.githubusercontent.com/64928185/213290298-53a6faa3-d0b4-44e9-bc9f-372f0fe27173.png)

**Information (please complete the following information):**
- OS: macOS Ventura 13.1 (Apple M1)
- Browser: N/A (Chrome)
- `mkdocstrings` version: 0.19.1
- `mkdocstrings-python` version: 0.8.3

**Comment by pawamoy** [comment]
Thanks a lot for the detailed report and reproduction repository! This will help a lot :slightly_smiling_face: 
I'm fine with using Poetry, no worries. I'll let you know once I have something :slightly_smiling_face:

**Comment by pawamoy** [comment]
So, it seems that the compiled `quotonic.fock` module defines `getDim` but says it comes from `quotonic.utilities`. This last module is not compiled (it's a .py file), so it's parsed but there's no `getDim` function defined into it. We're now in this situation:

- `quotonic.fock.getDim` is an alias to `quotonic.utilities.getDim`
- `quotonic.utilities.getDim` does not exist
- when trying to render the object, mkdocstrings fails to get its kind since the alias cannot be resolved, and the kind defaults to `alias`
- there's no `alias.html` template: failure

Could it be possible to, rather than setting `quotonic.fock.getDim.__module__` to `quotonic.utilities`, set it to `quotonic.fock` and *actually import* `getDim` from `quotonic.fock` into `quotonic.utilities`?

```python
# utilities.py
from quotonic.fock import getDim
```

I feel like declaring an object in the compiled module and setting its `__module__` attribute to another module is taking a shortcut, and it prevents Griffe from correctly inspecting the module.

WDYT?

**Comment by pawamoy** [comment]
Ah, looking at the .pyx and .c file, I think the culprit is `memoized`. It's wrapping the memoized object and since it is itself defined in `utilities`, every wrapped objects appears to come from `utilities` as well :thinking:

**Comment by pawamoy** [comment]
I believe you can workaround this issue by defined the `__wrapped__` attribute in your `memoized` instances:

```python
class memoized:
    def __init__(self, func):
        self.func = self.__wrapped__ = func
        self.cache = {}
```

This will allow Griffe to unwrap it when inspecting the object :slightly_smiling_face:

**Comment by jewaniuk** [comment]
Thank you so much @pawamoy for helping with this issue! I agree that your suggestion has resolved it and that the issue was directly related to the `@memoized` decorator. I hope that this helps others using decorators in this manner, and want to thank you and your colleagues for this awesome project.

**Comment by nightwnvol** [comment]
Hi @pawamoy,

I'm trying to generate the documentation for a project containing a Cython module, but I encountered a `could not be found error`. My project has almost the same structure of the one discussed in this issue, so I attempted to replicate it and encountered the same error:
```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  DeprecationWarning: invalid escape sequence \m
             File "C:\Users\clori\Desktop\quotonic-public\venv\lib\site-packages\griffe\agents\visitor.py", line 177, in
           get_module
               top_node = compile(self.code, mode="exec", filename=str(self.filepath), flags=ast.PyCF_ONLY_AST,
           optimize=1)
             File "quotonic\clements.py", line 8, in
               """Model of a linear Mach-Zehnder interferometer mesh arranged in the Clements configuration.
INFO    -  DeprecationWarning: invalid escape sequence \m
             File "C:\Users\clori\Desktop\quotonic-public\venv\lib\site-packages\griffe\agents\visitor.py", line 177, in
           get_module
               top_node = compile(self.code, mode="exec", filename=str(self.filepath), flags=ast.PyCF_ONLY_AST,
           optimize=1)
             File "quotonic\clements.py", line 33, in
               """Initialization of a MZI mesh arranged in the Clements configuration.
ERROR   -  mkdocstrings: quotonic.aa could not be found
ERROR   -  Error reading page 'aa.md':
ERROR   -  Could not collect 'quotonic.aa'

Aborted with a BuildError!
```

My venv info:
- `mkdocs==1.5.2`
- `mkdocstrings==0.22.0`
- `mkdocstrings-python==1.6.0`
- `griffe==0.35.2`

Any insights or guidance you could provide would be greatly appreciated. Thank you!

**Comment by pawamoy** [comment]
Can you open a new issue with MkDocs verbose logs (`mkdocs build -v`) and a link to your repository if it is public please? Thanks!
