### ISSUE TITLE
How to support numpy-style References?

### ISSUE THREAD

**Issue by ZhiyuanChen** [mkdocstrings/mkdocstrings#524]
I was trying to add some [references])https://numpydoc.readthedocs.io/en/latest/format.html#references), however, it seems they are not correctly identified. 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/28757366/214206403-33f7c72e-516d-451e-98d2-b358b747b00e.png">

**Comment by pawamoy** [comment]
Numpy references (and the math notation I see in your screenshot) are clearly RST-inspired (if not actually RST): we don't support RST (reStructuredText). Indeed MkDocs is a Markdown docs framework, not an RST one. So this kind of markup specified in the Numpydoc style guide will never be supported :confused: 

I'd suggest switching to a style that does not assume any particular markup, such as the Google-style. Or push the Numpy maintainers to revise their spec to make it markup/tool agnostic.

An alternative to these Numpy references would be to use [footnotes](https://python-markdown.github.io/extensions/footnotes/) (see it documented in the [Material for MkDocs docs](https://squidfunk.github.io/mkdocs-material/reference/footnotes/)).

**Comment by ZhiyuanChen** [comment]
Thank you for your clarification~
