### ISSUE TITLE
Generate docs for README.md

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocstrings/mkdocstrings#538]
Apologies if this has been asked before.

I have a package I'd like to document with just some content in `README.md`, no full mkdocs site.

Is there an easy way to get mkdocstrings to generate markdown suitable to copy into the readme?

Two issues I've seen:
1. I would prefer not to setup a dummy mkdocs site that I'm not using
2. mkdocstrings needs to output markdown, not HTML to put into the md file

**Comment by samuelcolvin** [comment]
thanks for the reply, that sounds perfect.

**Comment by pawamoy** [comment]
You'll get access to a prototype very soon :wink:

**Comment by pawamoy** [comment]
https://github.com/pawamoy-insiders/griffe2md :tada: 

You can install it by following the instructions at https://mkdocstrings.github.io/griffe2md/insiders/installation/.
