### ISSUE TITLE
Show custom decorators on function signatures

### ISSUE THREAD

**Issue by a-recknagel** [mkdocstrings/mkdocstrings#543]
I noticed the following on functions decorated with `functools.cache`:

<img width="246" alt="Screenshot 2023-03-30 181803" src="https://user-images.githubusercontent.com/2063412/228900886-a097198d-e0c2-4bb0-a7eb-74c0d47d205e.png">

I think it looks really neat, and would love to have support for 1st or 3rd party decorators as well. Maybe as an option for `mkdocs.yml` or by adding something like `__docs_decorator_name__ = "my_deorator"` to the wrapped function that mkdcostrings could look for.

**Comment by pawamoy** [comment]
Hello, thanks for the feature request :slightly_smiling_face: 

Can you give examples of first or third-party decorators you would like to be supported?

**Comment by a-recknagel** [comment]
While trying to give examples, I noticed that the change would need to happen [in the griffe project](https://github.com/mkdocstrings/griffe/blob/7129477184f0b88d3bf165dfe8e1f6158c30914a/src/griffe/agents/visitor.py#L54-L68). I don't know how you guys organize, should I close this issue and re-post this over there?

**Comment by pawamoy** [comment]
That's fine, if needed I can move it myself across projects :slightly_smiling_face:

**Comment by a-recknagel** [comment]
Ok, I'll handle it then. Thank you for your work, it's a great project!
