### ISSUE TITLE
Is there any way to keep quotation mark?

### ISSUE THREAD

**Issue by HydrogenSulfate** [mkdocstrings/mkdocstrings#545]
I have an method which has a argument named `mode` of `Literal[str]` type
```python
Class Solver:
    ...
    @staticmethod
    def from_config(cfg: Dict[str, Any], mode: Literal["train", "eval"]) -> Solver:
        ...
    
    def train(...):


    def eval(...):
```

and mkdocstring will render the argument `mode` to quote the method `Solver.train` and `Solver.eval` as below
![image](https://user-images.githubusercontent.com/23737287/229727598-839b72bc-e9b4-43f7-a6d3-86787500e8ea.png)
But I expected it be rendered as 
```python
Literal["train", "eval"]
```

So how to make mkdocstring show `""` quote marker instead of code link?

Set docstring to `Literal[\"train\", \"eval\"]` seems not work

**Comment by pawamoy** [comment]
Hi @HydrogenSulfate! Do you import `Literal` from `typing_extensions`? I noticed the current code only supports it when imported from `typing`.

**Comment by HydrogenSulfate** [comment]
> Hi @HydrogenSulfate! Do you import `Literal` from `typing_extensions`? I noticed the current code only supports it when imported from `typing`.

Yes, I use `Literal` from package `typing_extensions` to limit the input argument to a specified string set.

**Comment by HydrogenSulfate** [comment]
> Hi @HydrogenSulfate! Do you import `Literal` from `typing_extensions`? I noticed the current code only supports it when imported from `typing`.

And another question is when the type hint including class it self, there will be a warning as below.
![image](https://user-images.githubusercontent.com/23737287/230712536-8c66f610-4150-4a38-b1f8-9801c1eef094.png)
![image](https://user-images.githubusercontent.com/23737287/230712578-1e1f5e05-7c49-46f2-9684-cd4a32ec6a35.png)

and subsequently get a wrong render result as below
![image](https://user-images.githubusercontent.com/23737287/230712605-50de4d96-45e5-47bb-bb91-107df01245d3.png)

So is there any plan to support typing_extensions? Thanks much for your reply anyway.

**Comment by pawamoy** [comment]
Yes, I've just added support for `typing_extensions.Literal`, will release soon.

For your second question, you need a space between `mesh` and the type in the docstring: `mesh (Union[str, Mesh])`.

**Comment by HydrogenSulfate** [comment]
> Yes, I've just added support for `typing_extensions.Literal`, will release soon.
> 
> For your second question, you need a space between the parameter name and its type in the docstring: `mesh (Union[str, Mesh])`.

Happy to see the great feature added, it will make it more convenient for docs writers...
Warning solved magically after inserting a space, thanks again 👍😁
