### ISSUE TITLE
New dependency on `typing_extensions`

### ISSUE THREAD

**Issue by jleibs** [mkdocstrings/mkdocstrings#548]
Appears this is a regression related to: 444ef32

**Describe the bug**
On python versions < 3.10 we now see an import error due to dependency on `typing_extensions`

**To Reproduce**
Run mkdocs with mkdocstrings plugin on python < 3.10

**Comment by pawamoy** [comment]
Indeed, my bad for not checking if it was included in the production dependencies! I'll push a fix asap. Thanks for reporting!

**Comment by pawamoy** [comment]
0.21.1 released with the missing dependency for Python less than 3.10.

**Comment by jleibs** [comment]
Awesome. Thanks for the speedy turnaround on the fix!
