### ISSUE TITLE
Support setup from pyproject.toml

### ISSUE THREAD

**Issue by mcarans** [mkdocstrings/mkdocstrings#553]
Thanks for your work on this project. I have a suggestion: it would be great if the configuration could be read from pyproject.toml as an alternative to having a separate file mkdocs.yml since pyproject.toml has become the standard place for configuration.

**Comment by pawamoy** [comment]
Hi @mcarans, unfortunately we don't have control over this: MkDocs expects configuration to exist in `mkdocs.yml`.

**Comment by mcarans** [comment]
Ok thanks, i have raised this upstream: https://github.com/mkdocs/mkdocs/issues/3178
