### ISSUE TITLE
Show source for type aliases

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [mkdocstrings/mkdocstrings#559]
Hey there! Thanks for your work on `mkdocstrings` 🙏 

I'm working on a project that defines some type aliases, e.g.:

```py
CSSPathType = Union[
    str,
    PurePath,
    List[Union[str, PurePath]],
]
"""Valid ways of specifying paths to CSS files."""
```

This alias is used elsewhere to annotate variables.
In my project docs, `CSSPathType` shows up, it is documented as "Valid types for CSS file paths", and other variables that are annotated with `CSSPathType` will link to it.

**However**, I will not get the most important piece of information I need, which is the actual types in the type alias!
Even when `show_source` is set to `True`.

Do you have any idea how I could get this information shown?

The image below shows the issue. What would be _really_ helpful was the actual definition of the attribute `CSSPathType`.

![Untitled](https://user-images.githubusercontent.com/5621605/233085216-9d62686c-cea5-4406-aac0-2f2ab01006d5.png)

**Comment by pawamoy** [comment]
Hey @rodrigogiraoserrao, thanks for the detailed report :slightly_smiling_face: 

Seems to be working fine on my end:

![attr-value](https://user-images.githubusercontent.com/3999221/233803998-f251305c-da0e-494b-b690-55fcaea7d1ba.png)

I believe you're using custom templates: maybe you forgot some part of the original template for attributes?
