### ISSUE TITLE
MkDocStrings not showing aliased paths for methods 

### ISSUE THREAD

**Issue by phil65** [mkdocstrings/mkdocstrings#599]
Let´s say I have a class definied in a submodule:
`a.b.Class`

To make it more user-friendly, I import that class to the top-level module `a`:
(`from .b import Class` in `__init__.py` of `a`)

Using `::: a.Class` works fine in this case and shows the aliased path as a header,
when using `::: a.Class.method` though, it will show the un-aliased path as header. (`a.b.Class.method`)
Would be great if it would show `a.Class.method`
Thank you!

**Comment by pawamoy** [comment]
Same as https://github.com/mkdocstrings/python/issues/90, will keep open for visibility, thanks :slightly_smiling_face:
