### ISSUE TITLE
Documentation for watching source code directories

### ISSUE THREAD

**Issue by Epithumia** [mkdocstrings/mkdocstrings#604]
**Description**

The documentation (and, in fact, the README) state that:
> [Watch source code directories:](https://mkdocstrings.github.io/usage/#watch-directories) you can tell mkdocstrings to add directories to be watched by MkDocs when serving the documentation, for auto-reload.

However, the link sends to an non-existing section of the documentation with no explanation. After some googling, I found a cached version of that documentation page that says this was deprecated in favor of the watch option of mkdocs. I suggest that either this paragraph (in the README and the doc index) be removed (since it's a mkdocs feature), or updated to direct the user to the proper reference (https://www.mkdocs.org/user-guide/configuration/#live-reloading).

**Comment by pawamoy** [comment]
You're right, I'll update it, thanks for the heads up :slightly_smiling_face:

**Comment by pawamoy** [comment]
README updated, thansk again.
