### ISSUE TITLE
Python mkdocstrings - show_source

### ISSUE THREAD

**Issue by MrSniFo** [mkdocstrings/mkdocstrings#608]
I've encountered an issue with `mkdocstrings`, specifically related to the `show_source` feature. Despite disabling it works when using `mkdocs serve` locally, the problem persists when I've published my documentation on ReadtheDocs. Notably, all other elements of the documentation seem to be functioning correctly.

For reference, you can access my repository here: [GitHub Repository](https://github.com/MrSniFo/Twitchify/tree/main/docs), and the live documentation is available at this link: [Read the Docs Documentation](https://twitchify.readthedocs.io/en/latest/reference/models/).

**Comment by pawamoy** [comment]
I suppose it simply needed a few minutes of waiting and a browser refresh :slightly_smiling_face: 
Thanks for coming back and closing the issue!
