### ISSUE TITLE
bug: `templates` of `custom_templates` setting now needs to be an existing directory

### ISSUE THREAD

**Issue by Marenz** [mkdocstrings/mkdocstrings#634]
### Description of the bug

After updating to the latest version 0.24.0, I am getting the error

```
Config value 'plugins': Plugin 'mkdocstrings' option 'custom_templates': The path 'templates' isn't an existing directory.
```

Apparently the `templates` dir needs to exist now? 
Is that new requirement a desired feature or can this be considered a bug/regression?

**Comment by Marenz** [comment]
probably because of this new change: https://github.com/mkdocstrings/mkdocstrings/compare/0.23.0...0.24.0#diff-3968cbe3b57ebe74c208010a8eb7087459b75fe8d4e7bc5a29a30a882c5e4281R92

**Comment by pawamoy** [comment]
Hey, thanks for the report.

Yes, you correctly identified the change that is responsible for this. Previously, the templates folder was relative to the current working directory (which was incorrect behavior), now it is relative to the config file directory. To avoid silent breakages, it now requires that the directory exists. I suppose it's a bit brutal and we could probably have made the experience smoother, sorry for that :confused: 

Is there a use-case where you'd want to specify a custom templates directory that does not exist (yet)?

**Comment by Marenz** [comment]
We [have a project](https://github.com/frequenz-floss/frequenz-repo-config-python) that generates a default setup for git repositories, including documentation generation and it sets this as default.

It's nothing we can't work around and mostly a thing of minor (in)convenience I'd say.

**Comment by pawamoy** [comment]
I see, thanks. I suppose you can create the empty templates folder and track it in git as a workaround indeed. Or remove the `custom_templates` setting from mkdocs.yml.

Then I'll close this as requiring the directory to exist is the new desired behavior :slightly_smiling_face:
