### ISSUE TITLE
TypeScript handler

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#636]
### Is your feature request related to a problem? Please describe.
Opening for visibility.

### Describe the solution you'd like
A TypeScript handler.

### Additional context
Could use [api-extractor](https://api-extractor.com/)

---

@squidfunk @samuelcolvin could you describe what objects you would like to document in API refs? Do you have examples of API refs for TypeScript libraries that I could draw inspiration from? For example, looking at [sp-core-library](https://learn.microsoft.com/en-us/javascript/api/sp-core-library?view=sp-typescript-latest), I see that we should document classes (+ methods and properties), interfaces (+ methods and properties), type aliases, enumerations (+ fields). Maybe also "modules" and "variables"?

Also, could let me know if API Extractor  would fit your workflow/projects? If not, I can write an extractor in Python (I actually already started), but that will take more time.

Also also, it would be great if experienced TypeScript devs could share documents about file layouts and conventions regarding TypeScript packaging and exposing public APIs :slightly_smiling_face: 

---

*Notes to myself*

- https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c
- https://stackoverflow.com/questions/51131898/what-is-the-difference-between-type-and-class-in-typescript/51132333#51132333

**Comment by squidfunk** [comment]
For me, it's packages in a mono repo ([example](https://github.com/squidfunk/mono)), then in each package all exported functions incl. their signatures, as well as interfaces, types and exported variables. So, taking [one of my projects](https://github.com/squidfunk/mono/tree/master/packages/mono-esbuild), basically the top-level export:

<img width="422" alt="Bildschirm­foto 2023-12-02 um 17 12 53" src="https://github.com/mkdocstrings/mkdocstrings/assets/932156/68604377-9a70-4e20-b418-af81561e4831">

**Comment by kylebarron** [comment]
Also in related prior work for research: [Typedoc](https://github.com/TypeStrong/typedoc)

**Comment by kylebarron** [comment]
I don't know the internals of mkdocstrings and how handlers work, but I think the `--json` output flag of `typedoc` could be really useful for this. I don't know API extractor well, but I'd wager that `typedoc` might be better for this because it's already focused on documentation. 

I have a TypeScript project that has existing typedoc-based documentation ([hosted online here](https://kylebarron.dev/parquet-wasm/)). And here attached [docs.json](https://github.com/mkdocstrings/mkdocstrings/files/13891039/docs.json) is the JSON output from typedoc. (I ran `yarn typedoc --json docs.json` from the root of the project). typedoc's JSON output is [described here](https://typedoc.org/options/output/#json) with its own output on typedoc's source [here](https://typedoc.org/api/docs.json).

Maybe this is helpful here?

**Comment by pawamoy** [comment]
That is super helpful, thanks a lot! I came across Typedoc 3 weeks ago, when someone pointed me to it in [this tsdocs issue](https://github.com/pastelsky/tsdocs/issues/10), but didn't get time to try it yet. It looks exactly like the kind of tool a mkdocstrings handler could use :slightly_smiling_face:

**Comment by pawamoy** [comment]
@kylebarron Here's my experience:

- If there's a tool that reads this language's sources and outputs JSON (or any other serialized format really), then it's easy (there's typedoc for TypeScript, I'm working on its integration in a handler in https://github.com/mkdocstrings/griffe-typedoc (public/empty interface for the insiders repo :wink:)
- If there's no such tool, then it is still possible to use treesitter to write an AST visitor that builds the required API data from sources. It just needs a bit of fiddling to transpose the serialized data into Python objects, for use in Jinja templates. Before I learned about typedoc (thanks again!), I started working on that too, in https://github.com/mkdocstrings/griffe-typescript (again, public facing repo). How easy it is then depends on one's knowledge of the language in question. Since I don't know TypeScript, this would have been hard (I would have made wrong choices in data structures for example) or long to get a prototype (needing help from others who know the language better).

If you're willing to help, I can give you collaboration access to the relevant repositories, and we'll chat there in issues, and in return I can give you free access to Insiders. Let me know what you think (feel free to drop me a message on Gitter/Matrix or at pawamoy@pm.me) :slightly_smiling_face:

**Comment by pawamoy** [comment]
@samuelcolvin on what repository of yours could I test the handler?

**Comment by samuelcolvin** [comment]
It was FastUI, but I haven't got around to writing them yet. Sorry.

**Comment by pawamoy** [comment]
No worries, just wanted to make sure. Docstrings are not the most difficult part anyway. I'll start testing on FastUI :slightly_smiling_face:

**Comment by pawamoy** [comment]
@samuelcolvin I've published a first prototype. Insiders have gained access to it.

If you want to test it on FastUI:

```bash
# Enter your local clone.
cd FastUI

# Prepare a Python virtualenv.
python -m venv .venv
python -m pip install mkdocs mkdocs-material mkdocstrings

# If using PyPI Insiders (https://pawamoy.github.io/pypi-insiders/):
pypi-insiders server start
pypi-insiders repos add pawamoy-insiders/griffe-typedoc:griffe-typedoc
pypi-insiders repos add pawamoy-insiders/mkdocstrings-typescript:mkdocstrings-typescript
pypi-insiders repos update
python -m pip install mkdocstrings-typescript

# Else:
python -m pip install git+ssh://git@github.com/pawamoy-insiders/griffe-typedoc
python -m pip install git+ssh://git@github.com/pawamoy-insiders/mkdocstrings-typescript --no-deps
```

Then apply these changes: https://github.com/pydantic/FastUI/compare/main...pawamoy:FastUI:typedoc.
And run `mkdocs serve`.

**Comment by pawamoy** [comment]
@squidfunk you can follow a similar approach for your `mono` repo, my changes are here: https://github.com/squidfunk/mono/compare/spike/typedoc...pawamoy:mono:spike/typedoc.

**Comment by pawamoy** [comment]
Keep in mind this is a very early prototype, the rendered docs are super raw :sweat_smile:

**Comment by pawamoy** [comment]
Closing since we now have a first version of the handler. Open new issues in https://github.com/mkdocstrings/typescript.
