### ISSUE TITLE
How to add the label for "attribute" vs "method" in the reference documentation?

### ISSUE THREAD

**Issue by AlessandroMondin00** [mkdocstrings/mkdocstrings#638]
Currently this is my `mkdocs.yml`: <br>
<img width="758" alt="Screenshot 2023-12-15 at 17 11 11" src="https://github.com/mkdocstrings/mkdocstrings/assets/129836202/d99d3d45-f2a1-4663-9b6d-765666864d8a">

After rendering, the reference documentation results as in the image below: attribute and methods have no label to describe what is what. <br>
<img width="662" alt="Screenshot 2023-12-15 at 17 12 59" src="https://github.com/mkdocstrings/mkdocstrings/assets/129836202/bca4e171-920d-4c0d-934d-6a9939138166">
<br>
What I would like to obtain is a label that describes whether an item is an attribute or a method like in FastApi documentation as in the image below. <br>
<img width="738" alt="Screenshot 2023-12-15 at 17 15 46" src="https://github.com/mkdocstrings/mkdocstrings/assets/129836202/afbe014f-ab52-4bd2-bbec-daf2a0afe2a5">

**Comment by pawamoy** [comment]
This is an Insiders feature (docs: https://mkdocstrings.github.io/python/usage/configuration/headings/#show_symbol_type_heading). Hopefully it'll become available to everyone very soon, since the $500/month funding goal is almost reached :slightly_smiling_face:
