### ISSUE TITLE
bug: show_symbol_type_toc stopped working with markdown==3.6.0

### ISSUE THREAD

**Issue by daroczig** [mkdocstrings/mkdocstrings#662]
### Description of the bug

After upgrading the `markdown` package to the most recent version, the type is not shown in the ToC anymore. I think this is due to https://python-markdown.github.io/changelog/#refactor-toc-sanitation ("Refactor TOC Sanitation").

### To Reproduce

1. Enable `show_symbol_type_toc: true` in `mkdocs.yml`
2. Upgrade `markdown` to 3.6

    ```sh
    pip install --upgrade "markdown"
    ```

3. ToC doesn't include the type anymore .. revert `markdown to `3.5.2` for making it work again

    ```sh
    pip install "markdown==3.5.2"
    ```

### Expected behavior

`show_symbol_type_toc` works by showing the types in the table of contents (see screenshot):

![image](https://github.com/mkdocstrings/mkdocstrings/assets/495736/812f708d-ab22-44f0-a6c9-6552b6890f30)

### Environment information

```bash
$ python -m mkdocstrings.debug  # | xclip -selection clipboard

- __System__: Linux-6.8.1-arch1-1-x86_64-with-glibc2.39
- __Python__: cpython 3.11.8
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.24.1
```

**Comment by pawamoy** [comment]
Markdown 3.6 is supported by the latest version of mkdocstrings-python, try upgrading it :)

**Comment by daroczig** [comment]
Sorry for posting on v0.24.1 in the opening message; the CI tools are using the most recent versions. I've also upgraded on my localhost:

```sh
$ pip freeze | grep mkdocstrings 
mkdocstrings==0.24.2
mkdocstrings-python==1.9.2
```

Still, I don't see the type symbols showing up in the ToC with `markdown==3.6`.

**Comment by pawamoy** [comment]
OMG I released the fix with commented out code... must be tired. Will push a new release (mkdocstrings 0.24.3).

**Comment by AntoineD** [comment]
We have the same issue.

**Comment by daroczig** [comment]
Thank you so much, I highly appreciate it :bow:
