### ISSUE TITLE
harmless deprecation warnings

### ISSUE THREAD

**Issue by matanox** [mkdocstrings/mkdocstrings#676]
### Description of the bug
Many harmless deprecation warnings upon `mkdocs build`:

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: mkdocs/site
INFO    -  DeprecationWarning: The `get_logger` function is deprecated.
             File "venv-3.11.9/lib/python3.11/site-packages/_griffe/agents/nodes/runtime.py", line
           17, in <module>
               _logger = get_logger("griffe.agents.nodes._runtime")
             File "venv-3.11.9/lib/python3.11/site-packages/_griffe/logger.py", line 117, in
           get_logger
               warnings.warn("The `get_logger` function is deprecated.", DeprecationWarning, stacklevel=1)
INFO    -  DeprecationWarning: The `name` parameter is deprecated.
             File "venv-3.11.9/lib/python3.11/site-packages/_griffe/docstrings/google.py", line 49,
           in <module>
               _warn = docstring_warning("griffe.docstrings.google")
             File "venv-3.11.9/lib/python3.11/site-packages/_griffe/docstrings/utils.py", line 83,
           in docstring_warning
               warnings.warn("The `name` parameter is deprecated.", DeprecationWarning, stacklevel=1)
INFO    -  DeprecationWarning: Importing from `griffe.collections` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           15, in <module>
               from griffe.collections import LinesCollection, ModulesCollection
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/collections.py", line 12, in
           __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.docstrings.parsers` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           16, in <module>
               from griffe.docstrings.parsers import Parser
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/docstrings/parsers.py", line 12,
           in __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.exceptions` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           17, in <module>
               from griffe.exceptions import AliasResolutionError
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/exceptions.py", line 12, in
           __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.extensions` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           18, in <module>
               from griffe.extensions import load_extensions
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/extensions/__init__.py", line 12,
           in __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.loader` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           19, in <module>
               from griffe.loader import GriffeLoader
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/loader.py", line 12, in
           __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.logger` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           20, in <module>
               from griffe.logger import patch_loggers
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/logger.py", line 12, in
           __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.dataclasses` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/rendering.py",
           line 15, in <module>
               from griffe.dataclasses import Alias, Object
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/dataclasses.py", line 12, in
           __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: Importing from `griffe.docstrings.dataclasses` is deprecated. Import from `griffe` directly instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/rendering.py",
           line 16, in <module>
               from griffe.docstrings.dataclasses import (
             File "venv-3.11.9/lib/python3.11/site-packages/griffe/docstrings/dataclasses.py", line
           12, in __getattr__
               warnings.warn(
INFO    -  DeprecationWarning: The `patch_loggers` function is deprecated. Use `patch_logger` instead.
             File
           "venv-3.11.9/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line
           50, in <module>
               patch_loggers(get_logger)
             File "venv-3.11.9/lib/python3.11/site-packages/_griffe/logger.py", line 133, in
           patch_loggers
               warnings.warn(
INFO    -  Documentation built in 1.03 seconds
```

### Environment information
```
- __System__: Linux-5.15.0-116-generic-x86_64-with-glibc2.35
- __Python__: cpython 3.11.9 (venv-3.11.9/bin/python)
- __Environment variables__:
- __Installed packages__:
- `mkdocstrings` v0.25.1
```

A hearty thank you mkdocstrings!

**Comment by pawamoy** [comment]
Hey, thanks, this is tracked here: https://github.com/mkdocstrings/mkdocstrings/issues/676 :slightly_smiling_face:

**Comment by swo** [comment]
> Hey, thanks, this is tracked here: #676 🙂

Is this a circular reference? I couldn't find another issue with this content

Another hearty thanks to mkdocs!

**Comment by pawamoy** [comment]
Damn, that's not the first time I paste the URL of the very same issue :sweat: I meant this one: https://github.com/mkdocstrings/python/issues/173.

**Comment by nikhilweee** [comment]
Even with the latest release I still get the following warnings.

```
DeprecationWarning: The `get_logger` function is deprecated.
DeprecationWarning: The `name` parameter is deprecated.
```

I'm pretty sure I have the latest versions of all libraries.

```
$ pip list | egrep "griffe|mkdocstrings"
mkdocstrings                       0.25.2
mkdocstrings-python                1.10.7
griffe                             0.48.0
$ python --version
Python 3.10.14
```

**Comment by pawamoy** [comment]
Oh yes, these last two warnings come from Griffe itself, which is forced to use its own deprecated API until v1. If you want to get rid of them before v1 is out, you can configure Python warnings, see https://docs.python.org/3/library/warnings.html (there are multiple ways). Ideally Griffe itself should hide those :thinking: I'll leave this open to keep it in mind. If I release other non v1 versions, I'll include this change.

**Comment by WolfgangFahl** [comment]
@pawamoy - thanks for pointing to the multiple ways to switch off the warnings. Unfortunately this is all greek to me but frustrating and annoying since if my docs script show output it is interpreted as warnings to exist. I will have to grep the output for warnings or switch off the deprecation messages but how do i do this from the command line? The ways described in the link above all seem to assume programmatic access. So for the time being mdocstrings would be the code that can do this so i'd appreciate a release that has an option or better even default to switch off these messages.

**Comment by pawamoy** [comment]
Hi @WolfgangFahl, sorry to hear about your troubles.

> since if my docs script show output it is interpreted as warnings to exist

Can you elaborate on that? I understand it as, you are grepping the output to make the command pass or fail depending on what is written? May I ask what's the use-case here?

**Comment by pawamoy** [comment]
So I'm not sure to understand why, but I can't control warnings at all:

- `mkdocs serve` always catches them and re-emit them as INFO logs
- `python -m mkdocs serve` always ignores them completely

**Comment by pawamoy** [comment]
OK, seems like MkDocs should guard it's warning filter under `if not sys.warnoptions` :slightly_smiling_face: I'll open an issue there.

**Comment by WolfgangFahl** [comment]
@pawamoy @matanox 
https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python already gives a hint what developers think about python warnings that show up out of blue air. That stackoverflow has +380k views for a reason.

My usecase is to systematically have all my open source projects checked for being consistent https://wiki.bitplan.com/index.php/PyOpenSourceProjects is what i am using for this. 

it gives me e.g. checkos -o WolfgangFahl --local 
  1:✅ 43/43:WolfgangFahl/nicegui_widgets→https://github.com/WolfgangFahl/nicegui_widgets
  2:✅ 43/43:WolfgangFahl/py-3rdparty-mediawiki→https://github.com/WolfgangFahl/py-3rdparty-mediawiki
  3:✅ 43/43:WolfgangFahl/py-sidif→https://github.com/WolfgangFahl/py-sidif
  4:✅ 43/43:WolfgangFahl/py-yprinciple-gen→https://github.com/WolfgangFahl/py-yprinciple-gen
  5:✅ 42/42:WolfgangFahl/pyCEURmake→https://github.com/WolfgangFahl/pyCEURmake
  6:✅ 43/43:WolfgangFahl/pyLoDStorage→https://github.com/WolfgangFahl/pyLoDStorage
  7:✅ 43/43:WolfgangFahl/pymediawikidocker→https://github.com/WolfgangFahl/pymediawikidocker
  8:✅ 43/43:WolfgangFahl/pyMetaModel→https://github.com/WolfgangFahl/pyMetaModel
  9:✅ 43/43:WolfgangFahl/pyOpenSourceProjects→https://github.com/WolfgangFahl/pyOpenSourceProjects
 10:✅ 43/43:WolfgangFahl/pySMWsync→https://github.com/WolfgangFahl/pySMWsync
 11:✅ 43/43:WolfgangFahl/pyThunderbird→https://github.com/WolfgangFahl/pyThunderbird
 12:✅ 43/43:WolfgangFahl/scan2wiki→https://github.com/WolfgangFahl/scan2wiki
 13:✅ 43/43:WolfgangFahl/snapquery→https://github.com/WolfgangFahl/snapquery
 
 One of the checks is to make sure the doc script is always used.  Currently that is not directly integrated int python solution but i intend to do so in the future and add a "cockpit" in which the health checks of the OS projects may be monitored.
 
 For the time being there is only a visual clue - if the docs script shows any output that is considered to be bad. 
 
 ```python
 #!/bin/bash
# create docs for a configurable project
# WF 2024-07-30 - updated

# Extract project name from pyproject.toml
PROJECT_NAME=$(grep "\[project\]" pyproject.toml -A1 | grep name | cut -d '=' -f2 | tr -d ' "')
PACKAGE_NAME=$(grep "\[tool.hatch.build.targets.wheel.sources\]" pyproject.toml -A1 | tail -1 | cut -d '=' -f2 | tr -d ' "')


# Function to print usage information
print_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -pr, --project NAME    Set the project name (default: $PROJECT_NAME)"
    echo "  -pa, --package NAME    Set the package name (default: $PACKAGE_NAME)"
    echo "  -d, --deploy          Deploy the documentation after building"
    echo "  -h, --help            Display this help message"
}

# Parse command line arguments
DEPLOY=false
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -pr|--project) PROJECT_NAME="$2"; shift ;;
        -pa|--package) PACKAGE_NAME="$2"; shift ;;
        -d|--deploy) DEPLOY=true ;;
        -h|--help) print_usage; exit 0 ;;
        *) echo "Unknown parameter: $1"; print_usage; exit 1 ;;
    esac
    shift
done

# Ensure we're in the correct directory
if [[ ! -d "$PACKAGE_NAME" ]]; then
    echo "Error: $PACKAGE_NAME package directory not found. Are you in the correct directory?"
    exit 1
fi

# Check if mkdocs is installed
if ! command -v mkdocs &> /dev/null; then
    pip install mkdocs mkdocs-material mkdocstrings[python]
fi

# Create or update mkdocs.yml
cat << EOF > mkdocs.yml
site_name: $PROJECT_NAME API Documentation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
            - sys.path.insert(0, os.path.abspath("."))
          selection:
            docstring_style: google
          rendering:
            show_source: true
nav:
  - API: index.md
EOF

# Create or update index.md
index_md=docs/index.md
mkdir -p docs
cat << EOF > $index_md
# $PROJECT_NAME API Documentation

::: $PACKAGE_NAME
    options:
      show_submodules: true
EOF

# Ignore DeprecationWarnings during build
export PYTHONWARNINGS="ignore::DeprecationWarning"

# Build the documentation
mkdocs build --config-file ./mkdocs.yml

# Deploy if requested
if [ "$DEPLOY" = true ]; then
    mkdocs gh-deploy --force --config-file ./mkdocs.yml
fi

echo "Documentation process completed for $PROJECT_NAME."
```

**Comment by pawamoy** [comment]
@WolfgangFahl thanks for the elaboration. I'm not sure what "showing up out of blue air" means. The script you shared doesn't seem to check the output of the `mkdocs` command, so I suppose this check is done one layer above, with some kind of allow-listing of output lines (the `pip`, `mkdocs build`, `mkdocs gh-deploy` and last `echo` lines all write to stdout).

By the way it seems you missed previous deprecation warnings since you're using `mkdocstrings-python` and the `selection` and `rendering` options, which were deprecated then removed. These options therefore have no effect, and it just happens that you're setting the default values for `docstring_style` and `show_source`. The `setup_commands` also has no effect and is, I suppose, a left-over from when mkdocstrings was internally using pytkdocs.

Anyway, next version of Griffe will prevent these last two deprecation warnings to be emitted, and I've opened an issue on MkDocs so users can regain control on Python warnings :slightly_smiling_face:

**Comment by WolfgangFahl** [comment]
@pawamoy - thanks for the answer -  the scripts i am using for software iam starting to use are often generated with AI help these days. This style of working obviously leads to using well known concepts (from the past). The pressure to have stable APIs and settings on software developers will IMO rise from this style of working because the inefficiency of unstable environments is getting clearer. Hope this ticket may be closed soon and my downstream pyOpenSourceProject will benefit ...

**Comment by pawamoy** [comment]
> The pressure to have stable APIs and settings on software developers will IMO rise from this style of working because the inefficiency of unstable environments is getting clearer.

Doesn't sound fun for FOSS maintainers 😀

**Comment by nikhilweee** [comment]
@pawamoy Unrelated question: How did you link a commit to this issue? I see that this issue was closed at the same time as https://github.com/mkdocstrings/griffe/commit/9922d741dc1f9538e5e5f00dd115b297665ac6f8 was pushed. AFAIK GitHub only lets you link issues to pull requests: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by pawamoy** [comment]
I closed this issue manually. And I referenced it in the commit by pasting its full URL :) I use Git trailers in my commit messages ^^
