### ISSUE TITLE
try to install the library

### ISSUE THREAD

**Issue by rraulf** [mkdocstrings/mkdocstrings#683]
### Discussed in https://github.com/mkdocstrings/mkdocstrings/discussions/682

<div type='discussions-op-text'>

<sup>Originally posted by **rraulf** August  2, 2024</sup>
I try to install the library (as in #680 @matanox) and get an error:

ERROR: Could not find a version that satisfies the requirement mkdocstring (from versions: none)
ERROR: No matching distribution found for mkdocstring

What is the solution?

Thanks!</div>

**Comment by pawamoy** [comment]
> mkdocstring

You're missing the last "s": `mkdocstrings` :slightly_smiling_face:
