### ISSUE TITLE
bug: `ClassVar` not showing up when using the python handler

### ISSUE THREAD

**Issue by rentruewang** [mkdocstrings/mkdocstrings#695]
### Description of the bug

The following:

```python
class F: pass
class A(ABC):
    f: ClassVar[F] = F()
```

does not show f as an attribute

### To Reproduce
Please see the above example.

### Full traceback

<details><summary>Full traceback</summary>

```python
PASTE TRACEBACK HERE
```

</details>

### Environment information

```bash
python -m mkdocstrings.debug  # | xclip -selection clipboard
```

- __System__: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.39
- __Python__: cpython 3.12.3 (/home/abcde/mkdocstrings/venv/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.26.1

**Comment by pawamoy** [comment]
Hi @rentruewang, thanks for the report. Unfortunaly I cannot reproduce the issue you describe.

```python
from abc import ABC
class F: pass
class A(ABC):
    f: ClassVar[F] = F()
    """Docs."""
```

![f](https://github.com/user-attachments/assets/31d937ad-fcba-4e4a-8a66-8ab9743cef07)

**Comment by rentruewang** [comment]
Thank you. That makes sense.
