### ISSUE TITLE
Inventory not working with "mkdocstrings-python>=1.12.0"

### ISSUE THREAD

**Issue by HelgeKrueger** [mkdocstrings/mkdocstrings#700]
### Description of the bug

The inventory works with mkdocstrings-python==1.11.0 but stops working with 1.12.

### To Reproduce

In attached project run `uv run mkdocs serve`. Then the `str` is a link.

[bug.zip](https://github.com/user-attachments/files/17446614/bug.zip)

If you change the mkdocstrings-python version to 1.12 in `pyproject.toml` and rerun `uv ru nmkdocs serve` the str is no longer a link.

**Comment by pawamoy** [comment]
Hi @HelgeKrueger, thank you for the report and reproduction archive, I was able to confirm the issue. Investigating :slightly_smiling_face:

**Comment by pawamoy** [comment]
Right, this is a regression, the cross-refs are only rendered when the `signature_crossrefs` setting is true. I'll fix this to maintain previous behavior.

**Comment by pawamoy** [comment]
Fixed in mkdocstrings-python v1.12.2
