### ISSUE TITLE
bug: Running 'make setup' fails dependency resolution

### ISSUE THREAD

**Issue by connesy** [mkdocstrings/mkdocstrings#706]
### Description of the bug
Running `make setup` locally in a fork of the repo fails dependency resolution.

### To Reproduce
```
# Fork and clone the repository
cd mkdostrings
make setup
```

### Full traceback
<details><summary>Full traceback</summary>

```bash
$ make setup
Installing dependencies (default environment)
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of mkdocstrings-python-legacy are available:
          mkdocstrings-python-legacy<=0.2.1
          mkdocstrings-python-legacy==0.2.2
          mkdocstrings-python-legacy==0.2.3
          mkdocstrings-python-legacy==0.2.4
      and mkdocstrings-python-legacy>=0.2.1,<=0.2.2 depends on your project, we can conclude that mkdocstrings-python-legacy>=0.2.1,<0.2.3 depends on your project.
      And because mkdocstrings-python-legacy>=0.2.3 depends on your project, we can conclude that mkdocstrings-python-legacy>=0.2.1 depends on your project.
      And because mkdocstrings[python-legacy] depends on mkdocstrings-python-legacy>=0.2.1 and your project requires mkdocstrings[python-legacy], we can conclude that your projects's requirements are unsatisfiable.

      hint: The package `mkdocstrings-python-legacy` depends on the package `mkdocstrings` but the name is shadowed by your project. Consider changing the name of the project.
make: *** [Makefile:28: setup] Error 1
```

</details>

### Environment information

```bash
$ python -V
Python 3.12.3
$ uv -V
uv 0.4.29
```

**Comment by connesy** [comment]
If I check out commit `651d176` (release `0.26.1`), `make setup` runs succesfully. It seems to be related to the switch to having dependencies in `pyproject.toml` as part of `0.26.2`.

**Comment by pawamoy** [comment]
Hi @connesy, thanks for the report, you're absolutely right, there's an issue with uv: https://github.com/astral-sh/uv/issues/8148. I'll create and publish proper packages on PyPI that demonstrate the issue, maybe it will make it more clear to Astral how it can be problematic :confused: In the meantime you could try pulling tags into your local clone by declaring the upstream remote and pulling them from it:

```bash
# Assuming you authenticate with SSH.
git remote add upstream git@github.com:mkdocstrings/mkdocstrings
git pull remote --tags
```

**Comment by connesy** [comment]
Thanks, that works :+1:

**Comment by connesy** [comment]
I've created a PR here with the additional instructions for setting up: https://github.com/mkdocstrings/mkdocstrings/pull/708
