### ISSUE TITLE
feature: add `options` inside module `members`

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocstrings/mkdocstrings#713]
To make mkdocstrings render correctly (e.g. including the module in the TOC in the right place), I'd like to be able to do:

```
::: my_package.my_module
    options:
      members:
        - name: my_thing
          options: 
            ...
```

Currently this fails with an error about how dict is not hashable - I suggest even if you don't allow it, some validation on the schema of `options` and user friendly error about what's wrong with how `options` is defined would be useful.

**Comment by pawamoy** [comment]
Thanks for the request @samuelcolvin. I'd put that under "fine-grain configuration, see https://github.com/mkdocstrings/mkdocstrings/issues/658 :slightly_smiling_face: Let me know if this suggestion is what you would prefer over the listed alternatives.

**Comment by samuelcolvin** [comment]
closing in favour of #658
