### ISSUE TITLE
C handler

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#97]
**Is your feature request related to a problem? Please describe.**
Opening for visibility.

**Describe the solution you'd like**
A C handler. For extensions written in C.

**Additional context**
Doxygen?

**Comment by suned** [comment]
Do I understand correctly that this issue is for supporting docstrings of Python C extensions? e.g compiled with Cython? I've been wondering about how to best support that with mkdocstrings. For the Cython use-case, i think a C handler is tricky because the docstrings are placed in strangely named C variables. It might be easier to import the extension type in python and print the `__doc__` attribute?

**Comment by 2bndy5** [comment]
>**Additional context**
Doxygen?

Just thought I'd throw this out there for anyone passing by: [doxybook2](https://github.com/matusnovak/doxybook2) (actively developed) could be used instead of this plugin with doxygen's XML output. Notice there is a python lib called "doxybook" on pypi, but it has gone stale since doxybook2 was developed in C++ (same developer).

**Comment by pawamoy** [comment]
@suned, I realize I never answered your question above: I'm very sorry. The issue was about supporting documentation of C code, generally. But since Python C extensions are C code, they could be supported by such a handler as well (correct me if I'm wrong).

@2bndy5, hi, thanks for the link to doxybook2! Nice project :slightly_smiling_face: 
And I see the project has a [JSON-ouput feature](https://github.com/matusnovak/doxybook2#generating-json-only), which means it coul definitely (and maybe easily) be integrated as a handler for mkdocstrings, in order to make it benefit from mkdocstrings features such as cross-references or markdown inline injection (instead of page generation).

**Comment by 2bndy5** [comment]
I'm so glad you're interested. I was afraid my comment sounded like spam.

**Comment by ZeroIntensity** [comment]
As I said in #665, I would be happy to try and implement this. Is there a good reference I can follow for writing a handler?

**Comment by pawamoy** [comment]
From #665:

> Hopefully this would be easy to implement? All there is to C is pretty much global variables, types, functions, and macros. I'm not sure how mkdocstrings handlers work, but I would imagine that it would be somewhat easy to implement via [pycparser](https://github.com/eliben/pycparser).

Thanks, pycparser looks like a good candidate indeed, for Python extensions at least.

> If you don't have the time, or would like to focus on another issue, I would be happy to try to implement this myself, but I would need some example code to follow on how to write a handler.

Thanks! 

So, handlers are basically a `collect` and a `render` method. The `collect` method takes an identifier and configuration options, extracts info from sources or compiled code and returns it how it wants. The `render` method takes what the `collect` method returned and renders it with Jinja templates. You can get inspiration from the Python handler itself. Where the Python handler uses Griffe, your Python/C handler would use `pycparser` (probably). Maybe you'll need an intermediate data representation layer to better play with Jinja templates.

To illustrate it, here's how your handler would compare to existing ones:

```
mkdocstrings
    python handler
        griffe (intermediate data representation)
            ast
    typescript handler
        griffe-typedoc (Python structs for TypeScript code)
            typedoc
    python/c handler
        (optional) intermediate data representation
            pycparser
```

To kickstart a handler, you can use our [handler template](https://github.com/mkdocstrings/handler-template) :slightly_smiling_face: 

You can start a 1-1 conversation on Matrix/Gitter with me if you'd like to ask quick questions while working on it :slightly_smiling_face:

**Comment by pawamoy** [comment]
Quick question: once compiled, C extensions expose Python objects, right? Griffe should already be able to handle those, as it supports dynamic analysis (importing modules and inspecting them). That however requires that the C extensions are compiled in order to build the docs. A solution built on pycparser would allow to build the docs without compiling the extensions :+1:

**Comment by ZeroIntensity** [comment]
> Quick comment: once compiled, C extensions expose Python objects, right? Griffe should already be able to handle those, as it supports dynamic analysis (importing modules and inspecting them). That however requires that the C extensions are compiled in order to build the docs. A solution built on pycparser would allow to build the docs without compiling the extensions :+1: 

Not necessarily. They can expose a module object via `PyInit_`, which can hold other Python objects, but they can expose just about anything they want to the shared object file.

**Comment by ZeroIntensity** [comment]
I think doxygen might be a bit much for mkdocstrings - it is *huge*, and those who need all of its features will just use its markdown output feature anyway. It's generally a specification for C++ code, so it's way more in-depth than it needs to be for a C handler. 

I'm going to implement the base features of doxygen that would be useful in C, but I won't use doxygen itself to do that - I'll just write the parser myself. If a separate C++ handler were to be written in the future, then doxygen itself could be used.

**Comment by pawamoy** [comment]
Yeah I agree, depending on / bundling Doxygen would be a bit brutal :sweat_smile: Definitely pick the tool of your choice or get some fun implementing a parser! Looking forward to see what you come up with :slightly_smiling_face:

**Comment by pawamoy** [comment]
Thanks to @ZeroIntensity we have a first version of a C handler. Very much experimental. Feel free to give us feedback here: https://github.com/mkdocstrings/c/issues.

**Comment by 2bndy5** [comment]
The code is private and the docs say nothing about dependencies. Does it use libclang? I'm just curious how this was implemented without doxygen.

**Comment by 2bndy5** [comment]
If it uses pycparser, then the docs should note that only C99 is fully supported ([link](https://github.com/eliben/pycparser#13which-version-of-c-does-pycparser-support)) while C11 is partially supported.

libclang can be made to use whatever C/C++ standard, but getting doc comments (which have to be extracted from regular comments) can be a pain because it practically requires traversing all tokens in the AST from libclang with consideration given to the context of the symbol being documented.

**Comment by ZeroIntensity** [comment]
Please report bugs! I haven't had time to sit down and fully stress test it yet -- I'm almost certain there are *many* issues.
